
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Rank
{
public partial class RankRewardConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Rank.RankRewardConfig> _dataMap;
    private readonly System.Collections.Generic.List<Rank.RankRewardConfig> _dataList;
    
    public RankRewardConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Rank.RankRewardConfig>(n);
        _dataList = new System.Collections.Generic.List<Rank.RankRewardConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Rank.RankRewardConfig _v;
            _v = global::cfg.Rank.RankRewardConfig.DeserializeRankRewardConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RewardId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Rank.RankRewardConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Rank.RankRewardConfig> DataList => _dataList;

    public Rank.RankRewardConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Rank.RankRewardConfig Get(int key) => _dataMap[key];
    public Rank.RankRewardConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

