
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Rank
{
public partial class RankInfoConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<RankType, Rank.RankInfoConfig> _dataMap;
    private readonly System.Collections.Generic.List<Rank.RankInfoConfig> _dataList;
    
    public RankInfoConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<RankType, Rank.RankInfoConfig>(n);
        _dataList = new System.Collections.Generic.List<Rank.RankInfoConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Rank.RankInfoConfig _v;
            _v = global::cfg.Rank.RankInfoConfig.DeserializeRankInfoConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RankId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<RankType, Rank.RankInfoConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Rank.RankInfoConfig> DataList => _dataList;

    public Rank.RankInfoConfig GetOrDefault(RankType key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Rank.RankInfoConfig Get(RankType key) => _dataMap[key];
    public Rank.RankInfoConfig this[RankType key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

