
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Rank
{
public sealed partial class RankInfoConfig : Luban.BeanBase
{
    public RankInfoConfig(ByteBuf _buf) 
    {
        RankId = (RankType)_buf.ReadInt();
        RankName = _buf.ReadString();
        OrderType = _buf.ReadBool();
        According = _buf.ReadInt();
        According_Ref = null;
        {int n0 = _buf.ReadSize(); GradeName = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); GradeName.Add(_e0);}}
        Refresh = (RankEnum)_buf.ReadInt();
        SettleTime = (RankEnum)_buf.ReadInt();
        ClearTime = (RankEnum)_buf.ReadInt();
        ClearSwith = _buf.ReadBool();
    }

    public static RankInfoConfig DeserializeRankInfoConfig(ByteBuf _buf)
    {
        return new Rank.RankInfoConfig(_buf);
    }

    /// <summary>
    /// 排行枚举
    /// </summary>
    public readonly RankType RankId;
    /// <summary>
    /// 排行名称
    /// </summary>
    public readonly string RankName;
    /// <summary>
    /// 表现类型
    /// </summary>
    public readonly bool OrderType;
    /// <summary>
    /// 排序依据
    /// </summary>
    public readonly int According;
    public Item.ItemInfoConfig According_Ref;
    /// <summary>
    /// 评分名称
    /// </summary>
    public readonly System.Collections.Generic.List<string> GradeName;
    /// <summary>
    /// 刷新时间
    /// </summary>
    public readonly RankEnum Refresh;
    /// <summary>
    /// 结算时间
    /// </summary>
    public readonly RankEnum SettleTime;
    /// <summary>
    /// 清榜时间
    /// </summary>
    public readonly RankEnum ClearTime;
    /// <summary>
    /// 结算后数据是否清除
    /// </summary>
    public readonly bool ClearSwith;
   
    public const int __ID__ = -547291938;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        According_Ref = tables.ItemInfoConfigCategory.GetOrDefault(According);
    }

    public override string ToString()
    {
        return "{ "
        + "RankId:" + RankId + ","
        + "RankName:" + RankName + ","
        + "OrderType:" + OrderType + ","
        + "According:" + According + ","
        + "GradeName:" + Luban.StringUtil.CollectionToString(GradeName) + ","
        + "Refresh:" + Refresh + ","
        + "SettleTime:" + SettleTime + ","
        + "ClearTime:" + ClearTime + ","
        + "ClearSwith:" + ClearSwith + ","
        + "}";
    }
}
}

