
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Rank
{
public sealed partial class RankRewardConfig : Luban.BeanBase
{
    public RankRewardConfig(ByteBuf _buf) 
    {
        RewardId = _buf.ReadInt();
        FansRankPointAdd = _buf.ReadFloat();
        {int n0 = _buf.ReadSize(); WeekRankReward = new System.Collections.Generic.List<ItemGroup>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ItemGroup _e0;  _e0 = global::cfg.ItemGroup.DeserializeItemGroup(_buf); WeekRankReward.Add(_e0);}}
        WeekRankRewardShow = _buf.ReadString();
        {int n0 = _buf.ReadSize(); PreviousWeekRankReward = new System.Collections.Generic.List<ItemGroup>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ItemGroup _e0;  _e0 = global::cfg.ItemGroup.DeserializeItemGroup(_buf); PreviousWeekRankReward.Add(_e0);}}
        PreviousWeekRankShow = _buf.ReadString();
        {int n0 = _buf.ReadSize(); MonthRankReward = new System.Collections.Generic.List<ItemGroup>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ItemGroup _e0;  _e0 = global::cfg.ItemGroup.DeserializeItemGroup(_buf); MonthRankReward.Add(_e0);}}
        {int n0 = _buf.ReadSize(); PreviousMonthRankReward = new System.Collections.Generic.List<ItemGroup>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ItemGroup _e0;  _e0 = global::cfg.ItemGroup.DeserializeItemGroup(_buf); PreviousMonthRankReward.Add(_e0);}}
        PreviousMonthRankShow = _buf.ReadString();
        {int n0 = _buf.ReadSize(); PreviousMilestoneReward = new System.Collections.Generic.List<ItemGroup>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ItemGroup _e0;  _e0 = global::cfg.ItemGroup.DeserializeItemGroup(_buf); PreviousMilestoneReward.Add(_e0);}}
        PreviousMilestoneShow = _buf.ReadString();
        {int n0 = _buf.ReadSize(); HallOfFameReward = new System.Collections.Generic.List<ItemGroup>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ItemGroup _e0;  _e0 = global::cfg.ItemGroup.DeserializeItemGroup(_buf); HallOfFameReward.Add(_e0);}}
        {int n0 = _buf.ReadSize(); MilestoneReward = new System.Collections.Generic.List<ItemGroup>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ItemGroup _e0;  _e0 = global::cfg.ItemGroup.DeserializeItemGroup(_buf); MilestoneReward.Add(_e0);}}
        MilestoneSignAdd = _buf.ReadInt();
        MilestoneShow = _buf.ReadString();
    }

    public static RankRewardConfig DeserializeRankRewardConfig(ByteBuf _buf)
    {
        return new Rank.RankRewardConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int RewardId;
    /// <summary>
    /// 积分加成
    /// </summary>
    public readonly float FansRankPointAdd;
    /// <summary>
    /// 七天榜奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemGroup> WeekRankReward;
    /// <summary>
    /// 七天榜奖励图片
    /// </summary>
    public readonly string WeekRankRewardShow;
    /// <summary>
    /// 上周榜奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemGroup> PreviousWeekRankReward;
    /// <summary>
    /// 上周榜奖励图片
    /// </summary>
    public readonly string PreviousWeekRankShow;
    /// <summary>
    /// 月榜奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemGroup> MonthRankReward;
    /// <summary>
    /// 上月榜奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemGroup> PreviousMonthRankReward;
    /// <summary>
    /// 上月榜奖励图片
    /// </summary>
    public readonly string PreviousMonthRankShow;
    /// <summary>
    /// 上里程榜奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemGroup> PreviousMilestoneReward;
    /// <summary>
    /// 上里程榜奖励图片
    /// </summary>
    public readonly string PreviousMilestoneShow;
    /// <summary>
    /// 名人堂奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemGroup> HallOfFameReward;
    /// <summary>
    /// 里程碑奖励
    /// </summary>
    public readonly System.Collections.Generic.List<ItemGroup> MilestoneReward;
    /// <summary>
    /// 里程碑签到加成
    /// </summary>
    public readonly int MilestoneSignAdd;
    /// <summary>
    /// 里程碑奖励图片
    /// </summary>
    public readonly string MilestoneShow;
   
    public const int __ID__ = 889169695;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        foreach (var _e in WeekRankReward) { _e?.ResolveRef(tables); }
        foreach (var _e in PreviousWeekRankReward) { _e?.ResolveRef(tables); }
        foreach (var _e in MonthRankReward) { _e?.ResolveRef(tables); }
        foreach (var _e in PreviousMonthRankReward) { _e?.ResolveRef(tables); }
        foreach (var _e in PreviousMilestoneReward) { _e?.ResolveRef(tables); }
        foreach (var _e in HallOfFameReward) { _e?.ResolveRef(tables); }
        foreach (var _e in MilestoneReward) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "RewardId:" + RewardId + ","
        + "FansRankPointAdd:" + FansRankPointAdd + ","
        + "WeekRankReward:" + Luban.StringUtil.CollectionToString(WeekRankReward) + ","
        + "WeekRankRewardShow:" + WeekRankRewardShow + ","
        + "PreviousWeekRankReward:" + Luban.StringUtil.CollectionToString(PreviousWeekRankReward) + ","
        + "PreviousWeekRankShow:" + PreviousWeekRankShow + ","
        + "MonthRankReward:" + Luban.StringUtil.CollectionToString(MonthRankReward) + ","
        + "PreviousMonthRankReward:" + Luban.StringUtil.CollectionToString(PreviousMonthRankReward) + ","
        + "PreviousMonthRankShow:" + PreviousMonthRankShow + ","
        + "PreviousMilestoneReward:" + Luban.StringUtil.CollectionToString(PreviousMilestoneReward) + ","
        + "PreviousMilestoneShow:" + PreviousMilestoneShow + ","
        + "HallOfFameReward:" + Luban.StringUtil.CollectionToString(HallOfFameReward) + ","
        + "MilestoneReward:" + Luban.StringUtil.CollectionToString(MilestoneReward) + ","
        + "MilestoneSignAdd:" + MilestoneSignAdd + ","
        + "MilestoneShow:" + MilestoneShow + ","
        + "}";
    }
}
}

