
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Rank
{
public sealed partial class SignRewardConfig : Luban.BeanBase
{
    public SignRewardConfig(ByteBuf _buf) 
    {
        SignRewardId = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); RankNumber = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RankNumber.Add(_e0);}}
        SignRewardShow = _buf.ReadString();
    }

    public static SignRewardConfig DeserializeSignRewardConfig(ByteBuf _buf)
    {
        return new Rank.SignRewardConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int SignRewardId;
    /// <summary>
    /// 里程碑排名
    /// </summary>
    public readonly System.Collections.Generic.List<int> RankNumber;
    /// <summary>
    /// 燃料展示
    /// </summary>
    public readonly string SignRewardShow;
   
    public const int __ID__ = -2082117840;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SignRewardId:" + SignRewardId + ","
        + "RankNumber:" + Luban.StringUtil.CollectionToString(RankNumber) + ","
        + "SignRewardShow:" + SignRewardShow + ","
        + "}";
    }
}
}

