
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Rank
{
public partial class SignRewardConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Rank.SignRewardConfig> _dataMap;
    private readonly System.Collections.Generic.List<Rank.SignRewardConfig> _dataList;
    
    public SignRewardConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Rank.SignRewardConfig>(n);
        _dataList = new System.Collections.Generic.List<Rank.SignRewardConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Rank.SignRewardConfig _v;
            _v = global::cfg.Rank.SignRewardConfig.DeserializeSignRewardConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.SignRewardId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Rank.SignRewardConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Rank.SignRewardConfig> DataList => _dataList;

    public Rank.SignRewardConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Rank.SignRewardConfig Get(int key) => _dataMap[key];
    public Rank.SignRewardConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

