
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Rank
{
public partial class StarRewardConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Rank.StarRewardConfig> _dataMap;
    private readonly System.Collections.Generic.List<Rank.StarRewardConfig> _dataList;
    
    public StarRewardConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Rank.StarRewardConfig>(n);
        _dataList = new System.Collections.Generic.List<Rank.StarRewardConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Rank.StarRewardConfig _v;
            _v = global::cfg.Rank.StarRewardConfig.DeserializeStarRewardConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.SignRewardId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Rank.StarRewardConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Rank.StarRewardConfig> DataList => _dataList;

    public Rank.StarRewardConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Rank.StarRewardConfig Get(int key) => _dataMap[key];
    public Rank.StarRewardConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

