
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Rank
{
public sealed partial class StarRewardConfig : Luban.BeanBase
{
    public StarRewardConfig(ByteBuf _buf) 
    {
        SignRewardId = _buf.ReadInt();
        RankId = (RankType)_buf.ReadInt();
        RankNumberShow = _buf.ReadString();
        SignRewardShow = _buf.ReadString();
    }

    public static StarRewardConfig DeserializeStarRewardConfig(ByteBuf _buf)
    {
        return new Rank.StarRewardConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int SignRewardId;
    /// <summary>
    /// 排行枚举
    /// </summary>
    public readonly RankType RankId;
    /// <summary>
    /// 排名展示
    /// </summary>
    public readonly string RankNumberShow;
    /// <summary>
    /// 星星数量
    /// </summary>
    public readonly string SignRewardShow;
   
    public const int __ID__ = -819177403;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SignRewardId:" + SignRewardId + ","
        + "RankId:" + RankId + ","
        + "RankNumberShow:" + RankNumberShow + ","
        + "SignRewardShow:" + SignRewardShow + ","
        + "}";
    }
}
}

