
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Rank
{
public sealed partial class VideoShowConfig : Luban.BeanBase
{
    public VideoShowConfig(ByteBuf _buf) 
    {
        VideoShowId = _buf.ReadInt();
        RankId = (RankType)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); RankNumber = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RankNumber.Add(_e0);}}
        VideoRes = _buf.ReadString();
    }

    public static VideoShowConfig DeserializeVideoShowConfig(ByteBuf _buf)
    {
        return new Rank.VideoShowConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int VideoShowId;
    /// <summary>
    /// 排行枚举
    /// </summary>
    public readonly RankType RankId;
    /// <summary>
    /// 排名
    /// </summary>
    public readonly System.Collections.Generic.List<int> RankNumber;
    /// <summary>
    /// 视频资源
    /// </summary>
    public readonly string VideoRes;
   
    public const int __ID__ = -162567752;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "VideoShowId:" + VideoShowId + ","
        + "RankId:" + RankId + ","
        + "RankNumber:" + Luban.StringUtil.CollectionToString(RankNumber) + ","
        + "VideoRes:" + VideoRes + ","
        + "}";
    }
}
}

