
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Rank
{
public sealed partial class WeekRewardShowConfig : Luban.BeanBase
{
    public WeekRewardShowConfig(ByteBuf _buf) 
    {
        ShowId = _buf.ReadInt();
        Time = _buf.ReadLong();
        Banner = _buf.ReadString();
        BannerText = _buf.ReadString();
        CarRewardShow = _buf.ReadString();
        ItemRewardShow = _buf.ReadString();
    }

    public static WeekRewardShowConfig DeserializeWeekRewardShowConfig(ByteBuf _buf)
    {
        return new Rank.WeekRewardShowConfig(_buf);
    }

    /// <summary>
    /// 奖励展示ID
    /// </summary>
    public readonly int ShowId;
    /// <summary>
    /// 生效时间
    /// </summary>
    public readonly long Time;
    /// <summary>
    /// 顶部图片
    /// </summary>
    public readonly string Banner;
    /// <summary>
    /// 顶部文本
    /// </summary>
    public readonly string BannerText;
    /// <summary>
    /// 周榜排名奖励-赛车皮肤
    /// </summary>
    public readonly string CarRewardShow;
    /// <summary>
    /// 周榜排名奖励-空缺皮肤
    /// </summary>
    public readonly string ItemRewardShow;
   
    public const int __ID__ = -2048259644;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ShowId:" + ShowId + ","
        + "Time:" + Time + ","
        + "Banner:" + Banner + ","
        + "BannerText:" + BannerText + ","
        + "CarRewardShow:" + CarRewardShow + ","
        + "ItemRewardShow:" + ItemRewardShow + ","
        + "}";
    }
}
}

