
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Rank
{
public partial class WeekRewardShowConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Rank.WeekRewardShowConfig> _dataMap;
    private readonly System.Collections.Generic.List<Rank.WeekRewardShowConfig> _dataList;
    
    public WeekRewardShowConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Rank.WeekRewardShowConfig>(n);
        _dataList = new System.Collections.Generic.List<Rank.WeekRewardShowConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Rank.WeekRewardShowConfig _v;
            _v = global::cfg.Rank.WeekRewardShowConfig.DeserializeWeekRewardShowConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ShowId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Rank.WeekRewardShowConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Rank.WeekRewardShowConfig> DataList => _dataList;

    public Rank.WeekRewardShowConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Rank.WeekRewardShowConfig Get(int key) => _dataMap[key];
    public Rank.WeekRewardShowConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

