
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Net
{
public sealed partial class LoginInfoConfig : Luban.BeanBase
{
    public LoginInfoConfig(ByteBuf _buf) 
    {
        Channel = (ChannelCmd)_buf.ReadInt();
        LoginChannel = _buf.ReadString();
        LoginChannelId = _buf.ReadString();
        AppID = _buf.ReadString();
        BaseUrl = _buf.ReadString();
        Logo = _buf.ReadString();
        Name = _buf.ReadString();
    }

    public static LoginInfoConfig DeserializeLoginInfoConfig(ByteBuf _buf)
    {
        return new Net.LoginInfoConfig(_buf);
    }

    /// <summary>
    /// 平台类型
    /// </summary>
    public readonly ChannelCmd Channel;
    /// <summary>
    /// 平台名称
    /// </summary>
    public readonly string LoginChannel;
    /// <summary>
    /// 平台ID
    /// </summary>
    public readonly string LoginChannelId;
    /// <summary>
    /// 应用ID
    /// </summary>
    public readonly string AppID;
    /// <summary>
    /// 请求服务器(当前程序在项目内区分 多个IP+端口）
    /// </summary>
    public readonly string BaseUrl;
    /// <summary>
    /// logo名称
    /// </summary>
    public readonly string Logo;
    /// <summary>
    /// logo文本名
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = 743875400;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Channel:" + Channel + ","
        + "LoginChannel:" + LoginChannel + ","
        + "LoginChannelId:" + LoginChannelId + ","
        + "AppID:" + AppID + ","
        + "BaseUrl:" + BaseUrl + ","
        + "Logo:" + Logo + ","
        + "Name:" + Name + ","
        + "}";
    }
}
}

