
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Net
{
public partial class NetInfoConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<ChannelCmd, Net.NetInfoConfig> _dataMap;
    private readonly System.Collections.Generic.List<Net.NetInfoConfig> _dataList;
    
    public NetInfoConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<ChannelCmd, Net.NetInfoConfig>(n);
        _dataList = new System.Collections.Generic.List<Net.NetInfoConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Net.NetInfoConfig _v;
            _v = global::cfg.Net.NetInfoConfig.DeserializeNetInfoConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Type, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<ChannelCmd, Net.NetInfoConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Net.NetInfoConfig> DataList => _dataList;

    public Net.NetInfoConfig GetOrDefault(ChannelCmd key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Net.NetInfoConfig Get(ChannelCmd key) => _dataMap[key];
    public Net.NetInfoConfig this[ChannelCmd key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

