
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Net
{
public sealed partial class NetInfoConfig : Luban.BeanBase
{
    public NetInfoConfig(ByteBuf _buf) 
    {
        Type = (ChannelCmd)_buf.ReadInt();
        LoadNet = _buf.ReadBool();
        NetUrl = _buf.ReadString();
    }

    public static NetInfoConfig DeserializeNetInfoConfig(ByteBuf _buf)
    {
        return new Net.NetInfoConfig(_buf);
    }

    /// <summary>
    /// 平台类型
    /// </summary>
    public readonly ChannelCmd Type;
    /// <summary>
    /// 是否读取在线配置
    /// </summary>
    public readonly bool LoadNet;
    /// <summary>
    /// 在线地址
    /// </summary>
    public readonly string NetUrl;
   
    public const int __ID__ = 918600764;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Type:" + Type + ","
        + "LoadNet:" + LoadNet + ","
        + "NetUrl:" + NetUrl + ","
        + "}";
    }
}
}

