
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public sealed partial class BuffMutexConfig : Luban.BeanBase
{
    public BuffMutexConfig(ByteBuf _buf) 
    {
        MutexId = (State)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); Mutex = new System.Collections.Generic.List<MutexChange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { MutexChange _e0;  _e0 = global::cfg.MutexChange.DeserializeMutexChange(_buf); Mutex.Add(_e0);}}
        {int n0 = _buf.ReadSize(); MutexState = new System.Collections.Generic.List<StateChange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { StateChange _e0;  _e0 = global::cfg.StateChange.DeserializeStateChange(_buf); MutexState.Add(_e0);}}
    }

    public static BuffMutexConfig DeserializeBuffMutexConfig(ByteBuf _buf)
    {
        return new Fight.BuffMutexConfig(_buf);
    }

    /// <summary>
    /// 互斥ID
    /// </summary>
    public readonly State MutexId;
    /// <summary>
    /// 参数互斥
    /// </summary>
    public readonly System.Collections.Generic.List<MutexChange> Mutex;
    /// <summary>
    /// 状态互斥
    /// </summary>
    public readonly System.Collections.Generic.List<StateChange> MutexState;
   
    public const int __ID__ = 2128767280;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        foreach (var _e in Mutex) { _e?.ResolveRef(tables); }
        foreach (var _e in MutexState) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "MutexId:" + MutexId + ","
        + "Mutex:" + Luban.StringUtil.CollectionToString(Mutex) + ","
        + "MutexState:" + Luban.StringUtil.CollectionToString(MutexState) + ","
        + "}";
    }
}
}

