
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public partial class BuffIndexConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Fight.BuffIndexConfig> _dataMap;
    private readonly System.Collections.Generic.List<Fight.BuffIndexConfig> _dataList;
    
    public BuffIndexConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Fight.BuffIndexConfig>(n);
        _dataList = new System.Collections.Generic.List<Fight.BuffIndexConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Fight.BuffIndexConfig _v;
            _v = global::cfg.Fight.BuffIndexConfig.DeserializeBuffIndexConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.BuffId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Fight.BuffIndexConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Fight.BuffIndexConfig> DataList => _dataList;

    public Fight.BuffIndexConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Fight.BuffIndexConfig Get(int key) => _dataMap[key];
    public Fight.BuffIndexConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

