
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public sealed partial class BuffIndexConfig : Luban.BeanBase
{
    public BuffIndexConfig(ByteBuf _buf) 
    {
        BuffId = _buf.ReadInt();
        Type = (BuffType)_buf.ReadInt();
        Name = _buf.ReadString();
        TargetType = (Target)_buf.ReadInt();
        ActiveNumber = _buf.ReadInt();
        Time = _buf.ReadFloat();
        Faction = _buf.ReadInt();
        StateValue = (State)_buf.ReadInt();
    }

    public static BuffIndexConfig DeserializeBuffIndexConfig(ByteBuf _buf)
    {
        return new Fight.BuffIndexConfig(_buf);
    }

    /// <summary>
    /// BUFFid
    /// </summary>
    public readonly int BuffId;
    /// <summary>
    /// buff类型
    /// </summary>
    public readonly BuffType Type;
    /// <summary>
    /// Buff名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 目标
    /// </summary>
    public readonly Target TargetType;
    /// <summary>
    /// 生效目标
    /// </summary>
    public readonly int ActiveNumber;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly float Time;
    /// <summary>
    /// 效果组
    /// </summary>
    public readonly int Faction;
    /// <summary>
    /// 状态变化
    /// </summary>
    public readonly State StateValue;
   
    public const int __ID__ = 956732995;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BuffId:" + BuffId + ","
        + "Type:" + Type + ","
        + "Name:" + Name + ","
        + "TargetType:" + TargetType + ","
        + "ActiveNumber:" + ActiveNumber + ","
        + "Time:" + Time + ","
        + "Faction:" + Faction + ","
        + "StateValue:" + StateValue + ","
        + "}";
    }
}
}

