
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public partial class BuffMutexConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<State, Fight.BuffMutexConfig> _dataMap;
    private readonly System.Collections.Generic.List<Fight.BuffMutexConfig> _dataList;
    
    public BuffMutexConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<State, Fight.BuffMutexConfig>(n);
        _dataList = new System.Collections.Generic.List<Fight.BuffMutexConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Fight.BuffMutexConfig _v;
            _v = global::cfg.Fight.BuffMutexConfig.DeserializeBuffMutexConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.MutexId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<State, Fight.BuffMutexConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Fight.BuffMutexConfig> DataList => _dataList;

    public Fight.BuffMutexConfig GetOrDefault(State key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Fight.BuffMutexConfig Get(State key) => _dataMap[key];
    public Fight.BuffMutexConfig this[State key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

