
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public sealed partial class DeviceStateConfig : Luban.BeanBase
{
    public DeviceStateConfig(ByteBuf _buf) 
    {
        CarState = (State)_buf.ReadInt();
        SpineAnimation = _buf.ReadString();
    }

    public static DeviceStateConfig DeserializeDeviceStateConfig(ByteBuf _buf)
    {
        return new Fight.DeviceStateConfig(_buf);
    }

    /// <summary>
    /// 载具状态
    /// </summary>
    public readonly State CarState;
    /// <summary>
    /// 对应spine中的动作
    /// </summary>
    public readonly string SpineAnimation;
   
    public const int __ID__ = 1954781279;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "CarState:" + CarState + ","
        + "SpineAnimation:" + SpineAnimation + ","
        + "}";
    }
}
}

