
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public sealed partial class DeviceInfoConfig : Luban.BeanBase
{
    public DeviceInfoConfig(ByteBuf _buf) 
    {
        DeviceId = _buf.ReadInt();
        DeviceName = _buf.ReadString();
        DeviceRes = _buf.ReadString();
        SpineSkin = _buf.ReadString();
        Size = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); NormalEffect = new System.Collections.Generic.List<Effect>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Effect _e0;  _e0 = global::cfg.Effect.DeserializeEffect(_buf); NormalEffect.Add(_e0);}}
        NameTitleBg = _buf.ReadString();
        {int n0 = _buf.ReadSize(); NameTitlePos = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); NameTitlePos.Add(_e0);}}
    }

    public static DeviceInfoConfig DeserializeDeviceInfoConfig(ByteBuf _buf)
    {
        return new Fight.DeviceInfoConfig(_buf);
    }

    /// <summary>
    /// 载具ID
    /// </summary>
    public readonly int DeviceId;
    /// <summary>
    /// 载具名称
    /// </summary>
    public readonly string DeviceName;
    /// <summary>
    /// 载具资源
    /// </summary>
    public readonly string DeviceRes;
    /// <summary>
    /// 对应皮肤
    /// </summary>
    public readonly string SpineSkin;
    /// <summary>
    /// 缩放大小
    /// </summary>
    public readonly int Size;
    /// <summary>
    /// 正常行驶车轮特效
    /// </summary>
    public readonly System.Collections.Generic.List<Effect> NormalEffect;
    /// <summary>
    /// 赛车自定义标签
    /// </summary>
    public readonly string NameTitleBg;
    /// <summary>
    /// 赛车定义标签偏移
    /// </summary>
    public readonly System.Collections.Generic.List<float> NameTitlePos;
   
    public const int __ID__ = 1946283748;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        foreach (var _e in NormalEffect) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "DeviceId:" + DeviceId + ","
        + "DeviceName:" + DeviceName + ","
        + "DeviceRes:" + DeviceRes + ","
        + "SpineSkin:" + SpineSkin + ","
        + "Size:" + Size + ","
        + "NormalEffect:" + Luban.StringUtil.CollectionToString(NormalEffect) + ","
        + "NameTitleBg:" + NameTitleBg + ","
        + "NameTitlePos:" + Luban.StringUtil.CollectionToString(NameTitlePos) + ","
        + "}";
    }
}
}

