
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public partial class DeviceStateConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<State, Fight.DeviceStateConfig> _dataMap;
    private readonly System.Collections.Generic.List<Fight.DeviceStateConfig> _dataList;
    
    public DeviceStateConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<State, Fight.DeviceStateConfig>(n);
        _dataList = new System.Collections.Generic.List<Fight.DeviceStateConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Fight.DeviceStateConfig _v;
            _v = global::cfg.Fight.DeviceStateConfig.DeserializeDeviceStateConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.CarState, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<State, Fight.DeviceStateConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Fight.DeviceStateConfig> DataList => _dataList;

    public Fight.DeviceStateConfig GetOrDefault(State key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Fight.DeviceStateConfig Get(State key) => _dataMap[key];
    public Fight.DeviceStateConfig this[State key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

