
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public partial class EffectInfoConfigCategory
{
    private readonly System.Collections.Generic.List<Fight.EffectInfoConfig> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), Fight.EffectInfoConfig> _dataMapUnion;

    public EffectInfoConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<Fight.EffectInfoConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Fight.EffectInfoConfig _v;
            _v = global::cfg.Fight.EffectInfoConfig.DeserializeEffectInfoConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), Fight.EffectInfoConfig>(n);
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.EffectId, _v.EffectSkin), _v);
        }
        PostInit();
    }

    public System.Collections.Generic.List<Fight.EffectInfoConfig> DataList => _dataList;

    public Fight.EffectInfoConfig Get(int EffectId, int EffectSkin) => _dataMapUnion.TryGetValue((EffectId, EffectSkin), out Fight.EffectInfoConfig __v) ? __v : default;
    
    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolve();
    }

    partial void PostInit();
    partial void PostResolve();
}

}

