
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public sealed partial class EffectInfoConfig : Luban.BeanBase
{
    public EffectInfoConfig(ByteBuf _buf) 
    {
        EffectId = _buf.ReadInt();
        EffectSkin = _buf.ReadInt();
        Type = (EffectType)_buf.ReadInt();
        EffectPoint = (PointType)_buf.ReadInt();
        if(_buf.ReadBool()){ RandArea = global::cfg.AreaValue.DeserializeAreaValue(_buf); } else { RandArea = null; }
        EffectRes = _buf.ReadString();
        SpineSkin = _buf.ReadString();
        Size = _buf.ReadInt();
        IsCarEffectDpShow = _buf.ReadInt();
    }

    public static EffectInfoConfig DeserializeEffectInfoConfig(ByteBuf _buf)
    {
        return new Fight.EffectInfoConfig(_buf);
    }

    /// <summary>
    /// 特效ID
    /// </summary>
    public readonly int EffectId;
    /// <summary>
    /// 特效皮肤ID
    /// </summary>
    public readonly int EffectSkin;
    /// <summary>
    /// 特效类型
    /// </summary>
    public readonly EffectType Type;
    /// <summary>
    /// 挂载点
    /// </summary>
    public readonly PointType EffectPoint;
    /// <summary>
    /// 随机偏移范围
    /// </summary>
    public readonly AreaValue RandArea;
    /// <summary>
    /// 特效资源
    /// </summary>
    public readonly string EffectRes;
    /// <summary>
    /// spine皮肤名称
    /// </summary>
    public readonly string SpineSkin;
    /// <summary>
    /// 缩放大小
    /// </summary>
    public readonly int Size;
    /// <summary>
    /// 配置挂载车的重复特效
    /// </summary>
    public readonly int IsCarEffectDpShow;
   
    public const int __ID__ = -1863517089;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        RandArea?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "EffectId:" + EffectId + ","
        + "EffectSkin:" + EffectSkin + ","
        + "Type:" + Type + ","
        + "EffectPoint:" + EffectPoint + ","
        + "RandArea:" + RandArea + ","
        + "EffectRes:" + EffectRes + ","
        + "SpineSkin:" + SpineSkin + ","
        + "Size:" + Size + ","
        + "IsCarEffectDpShow:" + IsCarEffectDpShow + ","
        + "}";
    }
}
}

