
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public sealed partial class FactionGroupConfig : Luban.BeanBase
{
    public FactionGroupConfig(ByteBuf _buf) 
    {
        FactionId = _buf.ReadInt();
        GroupId = _buf.ReadInt();
        StartTime = _buf.ReadFloat();
        Interval = _buf.ReadFloat();
        ActiveNumber = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); ChangeValue = new System.Collections.Generic.List<BuffChange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { BuffChange _e0;  _e0 = global::cfg.BuffChange.DeserializeBuffChange(_buf); ChangeValue.Add(_e0);}}
        {int n0 = _buf.ReadSize(); BuffEffect = new System.Collections.Generic.List<Effect>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Effect _e0;  _e0 = global::cfg.Effect.DeserializeEffect(_buf); BuffEffect.Add(_e0);}}
    }

    public static FactionGroupConfig DeserializeFactionGroupConfig(ByteBuf _buf)
    {
        return new Fight.FactionGroupConfig(_buf);
    }

    /// <summary>
    /// 方法ID
    /// </summary>
    public readonly int FactionId;
    /// <summary>
    /// 效果组
    /// </summary>
    public readonly int GroupId;
    /// <summary>
    /// 触发时间
    /// </summary>
    public readonly float StartTime;
    /// <summary>
    /// 间隔时间
    /// </summary>
    public readonly float Interval;
    /// <summary>
    /// 生效次数
    /// </summary>
    public readonly int ActiveNumber;
    /// <summary>
    /// 参数变化
    /// </summary>
    public readonly System.Collections.Generic.List<BuffChange> ChangeValue;
    /// <summary>
    /// 挂载特效
    /// </summary>
    public readonly System.Collections.Generic.List<Effect> BuffEffect;
   
    public const int __ID__ = -1812865597;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        foreach (var _e in ChangeValue) { _e?.ResolveRef(tables); }
        foreach (var _e in BuffEffect) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "FactionId:" + FactionId + ","
        + "GroupId:" + GroupId + ","
        + "StartTime:" + StartTime + ","
        + "Interval:" + Interval + ","
        + "ActiveNumber:" + ActiveNumber + ","
        + "ChangeValue:" + Luban.StringUtil.CollectionToString(ChangeValue) + ","
        + "BuffEffect:" + Luban.StringUtil.CollectionToString(BuffEffect) + ","
        + "}";
    }
}
}

