
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public partial class FactionGroupConfigCategory
{
    private readonly System.Collections.Generic.List<Fight.FactionGroupConfig> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), Fight.FactionGroupConfig> _dataMapUnion;

    public FactionGroupConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<Fight.FactionGroupConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Fight.FactionGroupConfig _v;
            _v = global::cfg.Fight.FactionGroupConfig.DeserializeFactionGroupConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), Fight.FactionGroupConfig>(n);
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.FactionId, _v.GroupId), _v);
        }
        PostInit();
    }

    public System.Collections.Generic.List<Fight.FactionGroupConfig> DataList => _dataList;

    public Fight.FactionGroupConfig Get(int FactionId, int GroupId) => _dataMapUnion.TryGetValue((FactionId, GroupId), out Fight.FactionGroupConfig __v) ? __v : default;
    
    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolve();
    }

    partial void PostInit();
    partial void PostResolve();
}

}

