
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public partial class FightRoomConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Fight.FightRoomConfig> _dataMap;
    private readonly System.Collections.Generic.List<Fight.FightRoomConfig> _dataList;
    
    public FightRoomConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Fight.FightRoomConfig>(n);
        _dataList = new System.Collections.Generic.List<Fight.FightRoomConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Fight.FightRoomConfig _v;
            _v = global::cfg.Fight.FightRoomConfig.DeserializeFightRoomConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RoomId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Fight.FightRoomConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Fight.FightRoomConfig> DataList => _dataList;

    public Fight.FightRoomConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Fight.FightRoomConfig Get(int key) => _dataMap[key];
    public Fight.FightRoomConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

