
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public sealed partial class FightRoomConfig : Luban.BeanBase
{
    public FightRoomConfig(ByteBuf _buf) 
    {
        RoomId = _buf.ReadInt();
        RoomName = _buf.ReadString();
        RoomType = (FightRoomType)_buf.ReadInt();
        GameTime = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); FightSceneGroup = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); FightSceneGroup.Add(_e0);}}
        {int n0 = _buf.ReadSize(); TimeSceneInfo = new System.Collections.Generic.List<Planning>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Planning _e0;  _e0 = global::cfg.Planning.DeserializePlanning(_buf); TimeSceneInfo.Add(_e0);}}
        MaximumRange = _buf.ReadFloat();
        MaximumRangeShow = _buf.ReadFloat();
        {int n0 = _buf.ReadSize(); BaseDevice = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BaseDevice.Add(_e0);}}
    }

    public static FightRoomConfig DeserializeFightRoomConfig(ByteBuf _buf)
    {
        return new Fight.FightRoomConfig(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int RoomId;
    /// <summary>
    /// 房间名称
    /// </summary>
    public readonly string RoomName;
    /// <summary>
    /// 房间类型
    /// </summary>
    public readonly FightRoomType RoomType;
    /// <summary>
    /// 总游戏时长
    /// </summary>
    public readonly int GameTime;
    /// <summary>
    /// 场景组ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> FightSceneGroup;
    public System.Collections.Generic.List<Fight.SceneGroupInfoConfig> FightSceneGroup_Ref;
    /// <summary>
    /// 场景时长信息
    /// </summary>
    public readonly System.Collections.Generic.List<Planning> TimeSceneInfo;
    /// <summary>
    /// 最大里程数
    /// </summary>
    public readonly float MaximumRange;
    /// <summary>
    /// 最大里程数显示比例
    /// </summary>
    public readonly float MaximumRangeShow;
    /// <summary>
    /// 默认载具
    /// </summary>
    public readonly System.Collections.Generic.List<int> BaseDevice;
   
    public const int __ID__ = 2049883663;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        FightSceneGroup_Ref = new System.Collections.Generic.List<Fight.SceneGroupInfoConfig>();
        foreach (var _v in FightSceneGroup) { FightSceneGroup_Ref.Add(tables.SceneGroupInfoConfigCategory.GetOrDefault(_v)); }

        foreach (var _e in TimeSceneInfo) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "RoomId:" + RoomId + ","
        + "RoomName:" + RoomName + ","
        + "RoomType:" + RoomType + ","
        + "GameTime:" + GameTime + ","
        + "FightSceneGroup:" + Luban.StringUtil.CollectionToString(FightSceneGroup) + ","
        + "TimeSceneInfo:" + Luban.StringUtil.CollectionToString(TimeSceneInfo) + ","
        + "MaximumRange:" + MaximumRange + ","
        + "MaximumRangeShow:" + MaximumRangeShow + ","
        + "BaseDevice:" + Luban.StringUtil.CollectionToString(BaseDevice) + ","
        + "}";
    }
}
}

