
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public partial class SceneGroupInfoConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Fight.SceneGroupInfoConfig> _dataMap;
    private readonly System.Collections.Generic.List<Fight.SceneGroupInfoConfig> _dataList;
    
    public SceneGroupInfoConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Fight.SceneGroupInfoConfig>(n);
        _dataList = new System.Collections.Generic.List<Fight.SceneGroupInfoConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Fight.SceneGroupInfoConfig _v;
            _v = global::cfg.Fight.SceneGroupInfoConfig.DeserializeSceneGroupInfoConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.GroupId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Fight.SceneGroupInfoConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Fight.SceneGroupInfoConfig> DataList => _dataList;

    public Fight.SceneGroupInfoConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Fight.SceneGroupInfoConfig Get(int key) => _dataMap[key];
    public Fight.SceneGroupInfoConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

