
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public partial class SceneInfoConfigCategory
{
    private readonly System.Collections.Generic.List<Fight.SceneInfoConfig> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), Fight.SceneInfoConfig> _dataMapUnion;

    public SceneInfoConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<Fight.SceneInfoConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Fight.SceneInfoConfig _v;
            _v = global::cfg.Fight.SceneInfoConfig.DeserializeSceneInfoConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), Fight.SceneInfoConfig>(n);
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.SceneId, _v.GroupId), _v);
        }
        PostInit();
    }

    public System.Collections.Generic.List<Fight.SceneInfoConfig> DataList => _dataList;

    public Fight.SceneInfoConfig Get(int SceneId, int GroupId) => _dataMapUnion.TryGetValue((SceneId, GroupId), out Fight.SceneInfoConfig __v) ? __v : default;
    
    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolve();
    }

    partial void PostInit();
    partial void PostResolve();
}

}

