
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public sealed partial class SceneInfoConfig : Luban.BeanBase
{
    public SceneInfoConfig(ByteBuf _buf) 
    {
        SceneId = _buf.ReadInt();
        GroupId = _buf.ReadInt();
        LayerBG = global::cfg.LayerInfo.DeserializeLayerInfo(_buf);
        if(_buf.ReadBool()){ Layer0 = global::cfg.LayerInfo.DeserializeLayerInfo(_buf); } else { Layer0 = null; }
        if(_buf.ReadBool()){ Layer1 = global::cfg.LayerInfo.DeserializeLayerInfo(_buf); } else { Layer1 = null; }
        if(_buf.ReadBool()){ Layer2 = global::cfg.LayerInfo.DeserializeLayerInfo(_buf); } else { Layer2 = null; }
        if(_buf.ReadBool()){ Layer3 = global::cfg.LayerInfo.DeserializeLayerInfo(_buf); } else { Layer3 = null; }
        if(_buf.ReadBool()){ Layer4 = global::cfg.LayerInfo.DeserializeLayerInfo(_buf); } else { Layer4 = null; }
        if(_buf.ReadBool()){ Layer5 = global::cfg.LayerInfo.DeserializeLayerInfo(_buf); } else { Layer5 = null; }
        if(_buf.ReadBool()){ Layer6 = global::cfg.LayerInfo.DeserializeLayerInfo(_buf); } else { Layer6 = null; }
        if(_buf.ReadBool()){ RoadLine1 = global::cfg.LayerInfo.DeserializeLayerInfo(_buf); } else { RoadLine1 = null; }
        if(_buf.ReadBool()){ RoadLine2 = global::cfg.LayerInfo.DeserializeLayerInfo(_buf); } else { RoadLine2 = null; }
        if(_buf.ReadBool()){ RoadLine3 = global::cfg.LayerInfo.DeserializeLayerInfo(_buf); } else { RoadLine3 = null; }
    }

    public static SceneInfoConfig DeserializeSceneInfoConfig(ByteBuf _buf)
    {
        return new Fight.SceneInfoConfig(_buf);
    }

    /// <summary>
    /// 场景ID
    /// </summary>
    public readonly int SceneId;
    /// <summary>
    /// 场景组ID
    /// </summary>
    public readonly int GroupId;
    /// <summary>
    /// Layer_BG下的资源
    /// </summary>
    public readonly LayerInfo LayerBG;
    /// <summary>
    /// Layer_0下的资源
    /// </summary>
    public readonly LayerInfo Layer0;
    /// <summary>
    /// Layer_1下的资源
    /// </summary>
    public readonly LayerInfo Layer1;
    /// <summary>
    /// Layer_2下的资源
    /// </summary>
    public readonly LayerInfo Layer2;
    /// <summary>
    /// Layer_3下的资源
    /// </summary>
    public readonly LayerInfo Layer3;
    /// <summary>
    /// Layer_4下的资源
    /// </summary>
    public readonly LayerInfo Layer4;
    /// <summary>
    /// Layer_5下的资源
    /// </summary>
    public readonly LayerInfo Layer5;
    /// <summary>
    /// Layer_6下的资源
    /// </summary>
    public readonly LayerInfo Layer6;
    /// <summary>
    /// 跑道线1资源
    /// </summary>
    public readonly LayerInfo RoadLine1;
    /// <summary>
    /// 跑道线2资源
    /// </summary>
    public readonly LayerInfo RoadLine2;
    /// <summary>
    /// 跑道线3资源
    /// </summary>
    public readonly LayerInfo RoadLine3;
   
    public const int __ID__ = -286900962;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        LayerBG?.ResolveRef(tables);
        Layer0?.ResolveRef(tables);
        Layer1?.ResolveRef(tables);
        Layer2?.ResolveRef(tables);
        Layer3?.ResolveRef(tables);
        Layer4?.ResolveRef(tables);
        Layer5?.ResolveRef(tables);
        Layer6?.ResolveRef(tables);
        RoadLine1?.ResolveRef(tables);
        RoadLine2?.ResolveRef(tables);
        RoadLine3?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "SceneId:" + SceneId + ","
        + "GroupId:" + GroupId + ","
        + "LayerBG:" + LayerBG + ","
        + "Layer0:" + Layer0 + ","
        + "Layer1:" + Layer1 + ","
        + "Layer2:" + Layer2 + ","
        + "Layer3:" + Layer3 + ","
        + "Layer4:" + Layer4 + ","
        + "Layer5:" + Layer5 + ","
        + "Layer6:" + Layer6 + ","
        + "roadLine1:" + RoadLine1 + ","
        + "roadLine2:" + RoadLine2 + ","
        + "roadLine3:" + RoadLine3 + ","
        + "}";
    }
}
}

