
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Fight
{
public sealed partial class SceneGroupInfoConfig : Luban.BeanBase
{
    public SceneGroupInfoConfig(ByteBuf _buf) 
    {
        GroupId = _buf.ReadInt();
        IsUsed = _buf.ReadBool();
        SceneName = _buf.ReadString();
        Preview = _buf.ReadString();
        BtnBg = _buf.ReadString();
    }

    public static SceneGroupInfoConfig DeserializeSceneGroupInfoConfig(ByteBuf _buf)
    {
        return new Fight.SceneGroupInfoConfig(_buf);
    }

    /// <summary>
    /// 场景组ID
    /// </summary>
    public readonly int GroupId;
    /// <summary>
    /// 是否允许点击
    /// </summary>
    public readonly bool IsUsed;
    /// <summary>
    /// 场景名称
    /// </summary>
    public readonly string SceneName;
    /// <summary>
    /// 预览图
    /// </summary>
    public readonly string Preview;
    /// <summary>
    /// 按钮背景图
    /// </summary>
    public readonly string BtnBg;
   
    public const int __ID__ = 264371873;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "GroupId:" + GroupId + ","
        + "IsUsed:" + IsUsed + ","
        + "SceneName:" + SceneName + ","
        + "Preview:" + Preview + ","
        + "BtnBg:" + BtnBg + ","
        + "}";
    }
}
}

