
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Global
{
public sealed partial class ConstConfig : Luban.BeanBase
{
    public ConstConfig(ByteBuf _buf) 
    {
        TierStandard = _buf.ReadFloat();
        FirstTarget = _buf.ReadFloat();
        LastTarget = _buf.ReadFloat();
        TierTarget = _buf.ReadFloat();
        TeamTarget = _buf.ReadFloat();
        ChangeRoadCD = _buf.ReadInt();
        ChangeRoadTime = _buf.ReadInt();
        ChangeRoadRandom = _buf.ReadInt();
        SignBaseReward = global::cfg.ItemGroup.DeserializeItemGroup(_buf);
        PointStartAdd = _buf.ReadFloat();
        PointShareOut = _buf.ReadFloat();
        PointFirstGet = _buf.ReadFloat();
        PointSecondGet = _buf.ReadFloat();
        PointThirdGet = _buf.ReadFloat();
        FansJoinPct = _buf.ReadFloat();
        FansShareOut = _buf.ReadFloat();
        GameName = _buf.ReadString();
        {int n0 = _buf.ReadSize(); ItemsDefault = new System.Collections.Generic.List<ItemGroup>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ItemGroup _e0;  _e0 = global::cfg.ItemGroup.DeserializeItemGroup(_buf); ItemsDefault.Add(_e0);}}
        MaxPlayer = _buf.ReadInt();
        MinimumFortune = _buf.ReadInt();
        MinimumGoldPool = _buf.ReadInt();
        MinimumFortunePool = _buf.ReadInt();
        ItemFansValue = _buf.ReadInt();
        ItemFansAddRatio = _buf.ReadFloat();
        PoolSignCount = _buf.ReadInt();
        CustomizedSpareSkin = _buf.ReadInt();
    }

    public static ConstConfig DeserializeConstConfig(ByteBuf _buf)
    {
        return new Global.ConstConfig(_buf);
    }

    /// <summary>
    /// 梯队区分系数（第一名里程*N，与上一名差距大于该结果的自动降一梯队）
    /// </summary>
    public readonly float TierStandard;
    /// <summary>
    /// 第一名到屏幕右侧的距离系数（屏幕宽度*(1-N)，即80%*屏幕宽度）
    /// </summary>
    public readonly float FirstTarget;
    /// <summary>
    /// 最后一名到屏幕左侧的距离系数（屏幕宽度*N，即87%*屏幕宽度）
    /// </summary>
    public readonly float LastTarget;
    /// <summary>
    /// 梯队默认差距系数（保留4位小数）
    /// </summary>
    public readonly float TierTarget;
    /// <summary>
    /// 队列内差距系数（保留4位小数）
    /// </summary>
    public readonly float TeamTarget;
    /// <summary>
    /// 更换赛道的周期，单位：秒
    /// </summary>
    public readonly int ChangeRoadCD;
    /// <summary>
    /// 更换赛道的时长，单位：毫秒
    /// </summary>
    public readonly int ChangeRoadTime;
    /// <summary>
    /// 随机更换赛道的初始秒数（1到N），单位：秒
    /// </summary>
    public readonly int ChangeRoadRandom;
    /// <summary>
    /// 每日首次参与游戏给予的油桶基数（最终值需要乘上排行加成）
    /// </summary>
    public readonly ItemGroup SignBaseReward;
    /// <summary>
    /// 上一局积分继承到下一局的比例
    /// </summary>
    public readonly float PointStartAdd;
    /// <summary>
    /// 获胜时胜利队伍均分的比例（个人得分即积分*均分比例+积分*贡献占比）
    /// </summary>
    public readonly float PointShareOut;
    /// <summary>
    /// 第一名车队积分占比
    /// </summary>
    public readonly float PointFirstGet;
    /// <summary>
    /// 第二名车队积分占比
    /// </summary>
    public readonly float PointSecondGet;
    /// <summary>
    /// 第三名车队积分占比
    /// </summary>
    public readonly float PointThirdGet;
    /// <summary>
    /// 加入时取玩家的粉丝数量比值放入粉丝池中
    /// </summary>
    public readonly float FansJoinPct;
    /// <summary>
    /// 获胜时胜利队伍均分的比例（个人得分即粉丝*均分比例+粉丝*贡献占比）
    /// </summary>
    public readonly float FansShareOut;
    /// <summary>
    /// 游戏名称
    /// </summary>
    public readonly string GameName;
    /// <summary>
    /// 玩家默认背包数量
    /// </summary>
    public readonly System.Collections.Generic.List<ItemGroup> ItemsDefault;
    /// <summary>
    /// 游戏最大车队数
    /// </summary>
    public readonly int MaxPlayer;
    /// <summary>
    /// 保底粉丝
    /// </summary>
    public readonly int MinimumFortune;
    /// <summary>
    /// 保底金币池
    /// </summary>
    public readonly int MinimumGoldPool;
    /// <summary>
    /// 保底粉丝池
    /// </summary>
    public readonly int MinimumFortunePool;
    /// <summary>
    /// 道具粉丝值
    /// </summary>
    public readonly int ItemFansValue;
    /// <summary>
    /// 道具粉丝添加比例
    /// </summary>
    public readonly float ItemFansAddRatio;
    /// <summary>
    /// 奖池签到次数
    /// </summary>
    public readonly int PoolSignCount;
    /// <summary>
    /// 定制备用皮肤
    /// </summary>
    public readonly int CustomizedSpareSkin;
   
    public const int __ID__ = 181539514;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        SignBaseReward?.ResolveRef(tables);
        foreach (var _e in ItemsDefault) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "TierStandard:" + TierStandard + ","
        + "FirstTarget:" + FirstTarget + ","
        + "LastTarget:" + LastTarget + ","
        + "TierTarget:" + TierTarget + ","
        + "TeamTarget:" + TeamTarget + ","
        + "ChangeRoadCD:" + ChangeRoadCD + ","
        + "ChangeRoadTime:" + ChangeRoadTime + ","
        + "ChangeRoadRandom:" + ChangeRoadRandom + ","
        + "SignBaseReward:" + SignBaseReward + ","
        + "PointStartAdd:" + PointStartAdd + ","
        + "PointShareOut:" + PointShareOut + ","
        + "PointFirstGet:" + PointFirstGet + ","
        + "PointSecondGet:" + PointSecondGet + ","
        + "PointThirdGet:" + PointThirdGet + ","
        + "FansJoinPct:" + FansJoinPct + ","
        + "FansShareOut:" + FansShareOut + ","
        + "GameName:" + GameName + ","
        + "ItemsDefault:" + Luban.StringUtil.CollectionToString(ItemsDefault) + ","
        + "MaxPlayer:" + MaxPlayer + ","
        + "MinimumFortune:" + MinimumFortune + ","
        + "MinimumGoldPool:" + MinimumGoldPool + ","
        + "MinimumFortunePool:" + MinimumFortunePool + ","
        + "ItemFansValue:" + ItemFansValue + ","
        + "ItemFansAddRatio:" + ItemFansAddRatio + ","
        + "PoolSignCount:" + PoolSignCount + ","
        + "CustomizedSpareSkin:" + CustomizedSpareSkin + ","
        + "}";
    }
}
}

