
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Global
{
public partial class ConstConfigCategory
{

     private readonly Global.ConstConfig _data;

     public Global.ConstConfig Data => _data;

    public ConstConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::cfg.Global.ConstConfig.DeserializeConstConfig(_buf);
        PostInit();
    }


    /// <summary>
    /// 梯队区分系数（第一名里程*N，与上一名差距大于该结果的自动降一梯队）
    /// </summary>
     public float TierStandard => _data.TierStandard;
    /// <summary>
    /// 第一名到屏幕右侧的距离系数（屏幕宽度*(1-N)，即80%*屏幕宽度）
    /// </summary>
     public float FirstTarget => _data.FirstTarget;
    /// <summary>
    /// 最后一名到屏幕左侧的距离系数（屏幕宽度*N，即87%*屏幕宽度）
    /// </summary>
     public float LastTarget => _data.LastTarget;
    /// <summary>
    /// 梯队默认差距系数（保留4位小数）
    /// </summary>
     public float TierTarget => _data.TierTarget;
    /// <summary>
    /// 队列内差距系数（保留4位小数）
    /// </summary>
     public float TeamTarget => _data.TeamTarget;
    /// <summary>
    /// 更换赛道的周期，单位：秒
    /// </summary>
     public int ChangeRoadCD => _data.ChangeRoadCD;
    /// <summary>
    /// 更换赛道的时长，单位：毫秒
    /// </summary>
     public int ChangeRoadTime => _data.ChangeRoadTime;
    /// <summary>
    /// 随机更换赛道的初始秒数（1到N），单位：秒
    /// </summary>
     public int ChangeRoadRandom => _data.ChangeRoadRandom;
    /// <summary>
    /// 每日首次参与游戏给予的油桶基数（最终值需要乘上排行加成）
    /// </summary>
     public ItemGroup SignBaseReward => _data.SignBaseReward;
    /// <summary>
    /// 上一局积分继承到下一局的比例
    /// </summary>
     public float PointStartAdd => _data.PointStartAdd;
    /// <summary>
    /// 获胜时胜利队伍均分的比例（个人得分即积分*均分比例+积分*贡献占比）
    /// </summary>
     public float PointShareOut => _data.PointShareOut;
    /// <summary>
    /// 第一名车队积分占比
    /// </summary>
     public float PointFirstGet => _data.PointFirstGet;
    /// <summary>
    /// 第二名车队积分占比
    /// </summary>
     public float PointSecondGet => _data.PointSecondGet;
    /// <summary>
    /// 第三名车队积分占比
    /// </summary>
     public float PointThirdGet => _data.PointThirdGet;
    /// <summary>
    /// 加入时取玩家的粉丝数量比值放入粉丝池中
    /// </summary>
     public float FansJoinPct => _data.FansJoinPct;
    /// <summary>
    /// 获胜时胜利队伍均分的比例（个人得分即粉丝*均分比例+粉丝*贡献占比）
    /// </summary>
     public float FansShareOut => _data.FansShareOut;
    /// <summary>
    /// 游戏名称
    /// </summary>
     public string GameName => _data.GameName;
    /// <summary>
    /// 玩家默认背包数量
    /// </summary>
     public System.Collections.Generic.List<ItemGroup> ItemsDefault => _data.ItemsDefault;
    /// <summary>
    /// 游戏最大车队数
    /// </summary>
     public int MaxPlayer => 1000;
    /// <summary>
    /// 保底粉丝
    /// </summary>
     public int MinimumFortune => _data.MinimumFortune;
    /// <summary>
    /// 保底金币池
    /// </summary>
     public int MinimumGoldPool => _data.MinimumGoldPool;
    /// <summary>
    /// 保底粉丝池
    /// </summary>
     public int MinimumFortunePool => _data.MinimumFortunePool;
    /// <summary>
    /// 道具粉丝值
    /// </summary>
     public int ItemFansValue => _data.ItemFansValue;
    /// <summary>
    /// 道具粉丝添加比例
    /// </summary>
     public float ItemFansAddRatio => _data.ItemFansAddRatio;
    /// <summary>
    /// 奖池签到次数
    /// </summary>
     public int PoolSignCount => _data.PoolSignCount;
    /// <summary>
    /// 定制备用皮肤
    /// </summary>
     public int CustomizedSpareSkin => _data.CustomizedSpareSkin;
    
    public void ResolveRef(ConfigManager tables)
    {
        _data.ResolveRef(tables);
        PostResolve();
    }

    partial void PostInit();
    partial void PostResolve();
}

}

