
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Global
{
public partial class NoticeConfigCategory
{

     private readonly Global.NoticeConfig _data;

     public Global.NoticeConfig Data => _data;

    public NoticeConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::cfg.Global.NoticeConfig.DeserializeNoticeConfig(_buf);
        PostInit();
    }


    /// <summary>
    /// 默认字体大小配置
    /// </summary>
     public int DefaultFontSize => _data.DefaultFontSize;
    /// <summary>
    /// 默认字体颜色
    /// </summary>
     public string DefaultColor => _data.DefaultColor;
    /// <summary>
    /// 公告时间
    /// </summary>
     public string AnnouncementTime => _data.AnnouncementTime;
    /// <summary>
    /// 公告配置
    /// </summary>
     public string[] Announcement => _data.Announcement;
    
    public void ResolveRef(ConfigManager tables)
    {
        _data.ResolveRef(tables);
        PostResolve();
    }

    partial void PostInit();
    partial void PostResolve();
}

}

