
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Global
{
public sealed partial class NoticeConfig : Luban.BeanBase
{
    public NoticeConfig(ByteBuf _buf) 
    {
        DefaultFontSize = _buf.ReadInt();
        DefaultColor = _buf.ReadString();
        AnnouncementTime = _buf.ReadString();
        {int __n0 = _buf.ReadSize(); Announcement = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); Announcement[__index0] = __e0;}}
    }

    public static NoticeConfig DeserializeNoticeConfig(ByteBuf _buf)
    {
        return new Global.NoticeConfig(_buf);
    }

    /// <summary>
    /// 默认字体大小配置
    /// </summary>
    public readonly int DefaultFontSize;
    /// <summary>
    /// 默认字体颜色
    /// </summary>
    public readonly string DefaultColor;
    /// <summary>
    /// 公告时间
    /// </summary>
    public readonly string AnnouncementTime;
    /// <summary>
    /// 公告配置
    /// </summary>
    public readonly string[] Announcement;
   
    public const int __ID__ = 1757087909;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "DefaultFontSize:" + DefaultFontSize + ","
        + "DefaultColor:" + DefaultColor + ","
        + "AnnouncementTime:" + AnnouncementTime + ","
        + "Announcement:" + Luban.StringUtil.CollectionToString(Announcement) + ","
        + "}";
    }
}
}

