
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Global
{
public sealed partial class RandomNamesConfig : Luban.BeanBase
{
    public RandomNamesConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
    }

    public static RandomNamesConfig DeserializeRandomNamesConfig(ByteBuf _buf)
    {
        return new Global.RandomNamesConfig(_buf);
    }

    public readonly int Id;
    public readonly string Name;
   
    public const int __ID__ = 1340633692;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "}";
    }
}
}

