
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Global
{
public partial class RandomNamesConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Global.RandomNamesConfig> _dataMap;
    private readonly System.Collections.Generic.List<Global.RandomNamesConfig> _dataList;
    
    public RandomNamesConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Global.RandomNamesConfig>(n);
        _dataList = new System.Collections.Generic.List<Global.RandomNamesConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Global.RandomNamesConfig _v;
            _v = global::cfg.Global.RandomNamesConfig.DeserializeRandomNamesConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Global.RandomNamesConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Global.RandomNamesConfig> DataList => _dataList;

    public Global.RandomNamesConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Global.RandomNamesConfig Get(int key) => _dataMap[key];
    public Global.RandomNamesConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

