
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Global
{
public sealed partial class ShieldedLibraryConfig : Luban.BeanBase
{
    public ShieldedLibraryConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Word = _buf.ReadString();
    }

    public static ShieldedLibraryConfig DeserializeShieldedLibraryConfig(ByteBuf _buf)
    {
        return new Global.ShieldedLibraryConfig(_buf);
    }

    public readonly int Id;
    public readonly string Word;
   
    public const int __ID__ = -390267158;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Word:" + Word + ","
        + "}";
    }
}
}

