
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public partial class BadgeInfoConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Item.BadgeInfoConfig> _dataMap;
    private readonly System.Collections.Generic.List<Item.BadgeInfoConfig> _dataList;
    
    public BadgeInfoConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Item.BadgeInfoConfig>(n);
        _dataList = new System.Collections.Generic.List<Item.BadgeInfoConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Item.BadgeInfoConfig _v;
            _v = global::cfg.Item.BadgeInfoConfig.DeserializeBadgeInfoConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.BadgeId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Item.BadgeInfoConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Item.BadgeInfoConfig> DataList => _dataList;

    public Item.BadgeInfoConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Item.BadgeInfoConfig Get(int key) => _dataMap[key];
    public Item.BadgeInfoConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

