
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public sealed partial class BadgeInfoConfig : Luban.BeanBase
{
    public BadgeInfoConfig(ByteBuf _buf) 
    {
        BadgeId = _buf.ReadInt();
        FansNumbers = _buf.ReadInt();
        BadgeImage = _buf.ReadString();
        BadgeText = _buf.ReadString();
    }

    public static BadgeInfoConfig DeserializeBadgeInfoConfig(ByteBuf _buf)
    {
        return new Item.BadgeInfoConfig(_buf);
    }

    /// <summary>
    /// 徽章ID
    /// </summary>
    public readonly int BadgeId;
    /// <summary>
    /// 粉丝数量
    /// </summary>
    public readonly int FansNumbers;
    /// <summary>
    /// 对应徽章
    /// </summary>
    public readonly string BadgeImage;
    /// <summary>
    /// 对应文本
    /// </summary>
    public readonly string BadgeText;
   
    public const int __ID__ = -1736941384;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BadgeId:" + BadgeId + ","
        + "FansNumbers:" + FansNumbers + ","
        + "BadgeImage:" + BadgeImage + ","
        + "BadgeText:" + BadgeText + ","
        + "}";
    }
}
}

