
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public sealed partial class InputIndexConfig : Luban.BeanBase
{
    public InputIndexConfig(ByteBuf _buf) 
    {
        InputId = _buf.ReadInt();
        InputStr = _buf.ReadString();
        InputNumber = _buf.ReadInt();
        Icon = _buf.ReadString();
        InputRes = _buf.ReadString();
        InputAnimation = _buf.ReadString();
        Interactive = (InteractiveID)_buf.ReadInt();
        IsGift = _buf.ReadBool();
        AutoJoinRoom = _buf.ReadBool();
        Cmd = (ECmd)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); ExtendedInstructions = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ExtendedInstructions.Add(_e0);}}
        GetPoint = _buf.ReadFloat();
        Quantity = _buf.ReadInt();
        if(_buf.ReadBool()){ MaxNumOfSingleGame = _buf.ReadInt(); } else { MaxNumOfSingleGame = null; }
    }

    public static InputIndexConfig DeserializeInputIndexConfig(ByteBuf _buf)
    {
        return new Item.InputIndexConfig(_buf);
    }

    /// <summary>
    /// 指令ID
    /// </summary>
    public readonly int InputId;
    /// <summary>
    /// 事件名称
    /// </summary>
    public readonly string InputStr;
    /// <summary>
    /// 事件数量
    /// </summary>
    public readonly int InputNumber;
    /// <summary>
    /// 道具图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 道具使用框
    /// </summary>
    public readonly string InputRes;
    /// <summary>
    /// 道具使用动画
    /// </summary>
    public readonly string InputAnimation;
    /// <summary>
    /// 消息ID
    /// </summary>
    public readonly InteractiveID Interactive;
    /// <summary>
    /// 礼物类型
    /// </summary>
    public readonly bool IsGift;
    /// <summary>
    /// 是否自动加入
    /// </summary>
    public readonly bool AutoJoinRoom;
    /// <summary>
    /// 对应指令类型
    /// </summary>
    public readonly ECmd Cmd;
    /// <summary>
    /// 扩展指令
    /// </summary>
    public readonly System.Collections.Generic.List<string> ExtendedInstructions;
    /// <summary>
    /// 指令产生的基础积分
    /// </summary>
    public readonly float GetPoint;
    /// <summary>
    /// 达到指定数量触发
    /// </summary>
    public readonly int Quantity;
    /// <summary>
    /// 单局数量上限
    /// </summary>
    public readonly int? MaxNumOfSingleGame;
   
    public const int __ID__ = -1207974395;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "InputId:" + InputId + ","
        + "InputStr:" + InputStr + ","
        + "InputNumber:" + InputNumber + ","
        + "Icon:" + Icon + ","
        + "InputRes:" + InputRes + ","
        + "InputAnimation:" + InputAnimation + ","
        + "Interactive:" + Interactive + ","
        + "IsGift:" + IsGift + ","
        + "AutoJoinRoom:" + AutoJoinRoom + ","
        + "Cmd:" + Cmd + ","
        + "ExtendedInstructions:" + Luban.StringUtil.CollectionToString(ExtendedInstructions) + ","
        + "GetPoint:" + GetPoint + ","
        + "Quantity:" + Quantity + ","
        + "MaxNumOfSingleGame:" + MaxNumOfSingleGame + ","
        + "}";
    }
}
}

