
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public partial class InputIndexConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Item.InputIndexConfig> _dataMap;
    private readonly System.Collections.Generic.List<Item.InputIndexConfig> _dataList;
    
    public InputIndexConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Item.InputIndexConfig>(n);
        _dataList = new System.Collections.Generic.List<Item.InputIndexConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Item.InputIndexConfig _v;
            _v = global::cfg.Item.InputIndexConfig.DeserializeInputIndexConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.InputId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Item.InputIndexConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Item.InputIndexConfig> DataList => _dataList;

    public Item.InputIndexConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Item.InputIndexConfig Get(int key) => _dataMap[key];
    public Item.InputIndexConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

