
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public partial class ItemInfoConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Item.ItemInfoConfig> _dataMap;
    private readonly System.Collections.Generic.List<Item.ItemInfoConfig> _dataList;
    
    public ItemInfoConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Item.ItemInfoConfig>(n);
        _dataList = new System.Collections.Generic.List<Item.ItemInfoConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Item.ItemInfoConfig _v;
            _v = global::cfg.Item.ItemInfoConfig.DeserializeItemInfoConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Item.ItemInfoConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Item.ItemInfoConfig> DataList => _dataList;

    public Item.ItemInfoConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Item.ItemInfoConfig Get(int key) => _dataMap[key];
    public Item.ItemInfoConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

