
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public sealed partial class ItemInfoConfig : Luban.BeanBase
{
    public ItemInfoConfig(ByteBuf _buf) 
    {
        ItemId = _buf.ReadInt();
        ItemName = _buf.ReadString();
        Type = (ItemType)_buf.ReadInt();
        Icon = _buf.ReadString();
        {int n0 = _buf.ReadSize(); TypeValue = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TypeValue.Add(_e0);}}
        LimitTime = _buf.ReadInt();
    }

    public static ItemInfoConfig DeserializeItemInfoConfig(ByteBuf _buf)
    {
        return new Item.ItemInfoConfig(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly string ItemName;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly ItemType Type;
    /// <summary>
    /// 道具图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 道具类型值
    /// </summary>
    public readonly System.Collections.Generic.List<int> TypeValue;
    /// <summary>
    /// 道具有效时间
    /// </summary>
    public readonly int LimitTime;
   
    public const int __ID__ = -807781058;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemId:" + ItemId + ","
        + "ItemName:" + ItemName + ","
        + "Type:" + Type + ","
        + "Icon:" + Icon + ","
        + "TypeValue:" + Luban.StringUtil.CollectionToString(TypeValue) + ","
        + "LimitTime:" + LimitTime + ","
        + "}";
    }
}
}

