
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public sealed partial class SignInfoConfig : Luban.BeanBase
{
    public SignInfoConfig(ByteBuf _buf) 
    {
        SignId = _buf.ReadInt();
        ChannelSignID = _buf.ReadString();
        Gift = (InteractiveID)_buf.ReadInt();
        Price = _buf.ReadFloat();
        Channel = (ChannelCmd)_buf.ReadInt();
    }

    public static SignInfoConfig DeserializeSignInfoConfig(ByteBuf _buf)
    {
        return new Item.SignInfoConfig(_buf);
    }

    /// <summary>
    /// 礼物ID
    /// </summary>
    public readonly int SignId;
    /// <summary>
    /// 对应平台KEY
    /// </summary>
    public readonly string ChannelSignID;
    /// <summary>
    /// 礼物消息类型
    /// </summary>
    public readonly InteractiveID Gift;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly float Price;
    /// <summary>
    /// 平台类型
    /// </summary>
    public readonly ChannelCmd Channel;
   
    public const int __ID__ = 120247144;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SignId:" + SignId + ","
        + "ChannelSignID:" + ChannelSignID + ","
        + "Gift:" + Gift + ","
        + "Price:" + Price + ","
        + "Channel:" + Channel + ","
        + "}";
    }
}
}

