
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public sealed partial class StarInfoConfig : Luban.BeanBase
{
    public StarInfoConfig(ByteBuf _buf) 
    {
        StarId = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); RankNumber = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RankNumber.Add(_e0);}}
        StarBGRes = _buf.ReadString();
        StarUpRes = _buf.ReadString();
        FrameRes = _buf.ReadString();
    }

    public static StarInfoConfig DeserializeStarInfoConfig(ByteBuf _buf)
    {
        return new Item.StarInfoConfig(_buf);
    }

    /// <summary>
    /// 星级ID
    /// </summary>
    public readonly int StarId;
    /// <summary>
    /// 星级排名
    /// </summary>
    public readonly System.Collections.Generic.List<int> RankNumber;
    /// <summary>
    /// 星级底框
    /// </summary>
    public readonly string StarBGRes;
    /// <summary>
    /// 星级顶框
    /// </summary>
    public readonly string StarUpRes;
    /// <summary>
    /// 头像框
    /// </summary>
    public readonly string FrameRes;
   
    public const int __ID__ = 1815414205;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "StarId:" + StarId + ","
        + "RankNumber:" + Luban.StringUtil.CollectionToString(RankNumber) + ","
        + "StarBGRes:" + StarBGRes + ","
        + "StarUpRes:" + StarUpRes + ","
        + "FrameRes:" + FrameRes + ","
        + "}";
    }
}
}

