
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public partial class StoreConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, Item.StoreConfig> _dataMap;
    private readonly System.Collections.Generic.List<Item.StoreConfig> _dataList;
    
    public StoreConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Item.StoreConfig>(n);
        _dataList = new System.Collections.Generic.List<Item.StoreConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Item.StoreConfig _v;
            _v = global::cfg.Item.StoreConfig.DeserializeStoreConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.GoodsId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, Item.StoreConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Item.StoreConfig> DataList => _dataList;

    public Item.StoreConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Item.StoreConfig Get(int key) => _dataMap[key];
    public Item.StoreConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

