
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public sealed partial class StoreConfig : Luban.BeanBase
{
    public StoreConfig(ByteBuf _buf) 
    {
        GoodsId = _buf.ReadInt();
        Goods = global::cfg.ItemGroup.DeserializeItemGroup(_buf);
        Cost = global::cfg.ItemGroup.DeserializeItemGroup(_buf);
        CostItemPic = _buf.ReadString();
        CostName = _buf.ReadString();
        CostDay = _buf.ReadString();
    }

    public static StoreConfig DeserializeStoreConfig(ByteBuf _buf)
    {
        return new Item.StoreConfig(_buf);
    }

    /// <summary>
    /// 商品ID
    /// </summary>
    public readonly int GoodsId;
    /// <summary>
    /// 商品内容
    /// </summary>
    public readonly ItemGroup Goods;
    /// <summary>
    /// 消耗货币
    /// </summary>
    public readonly ItemGroup Cost;
    /// <summary>
    /// 图片名称
    /// </summary>
    public readonly string CostItemPic;
    /// <summary>
    /// 道具名字
    /// </summary>
    public readonly string CostName;
    /// <summary>
    /// 道具生效天数
    /// </summary>
    public readonly string CostDay;
   
    public const int __ID__ = -250374872;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        Goods?.ResolveRef(tables);
        Cost?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "GoodsId:" + GoodsId + ","
        + "Goods:" + Goods + ","
        + "Cost:" + Cost + ","
        + "CostItemPic:" + CostItemPic + ","
        + "CostName:" + CostName + ","
        + "CostDay:" + CostDay + ","
        + "}";
    }
}
}

