
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 区域坐标
/// </summary>
public sealed partial class AreaValue : Luban.BeanBase
{
    public AreaValue(ByteBuf _buf) 
    {
        X = _buf.ReadFloat();
        Y = _buf.ReadFloat();
    }

    public static AreaValue DeserializeAreaValue(ByteBuf _buf)
    {
        return new AreaValue(_buf);
    }

    /// <summary>
    /// X轴偏移范围
    /// </summary>
    public readonly float X;
    /// <summary>
    /// Y轴偏移范围
    /// </summary>
    public readonly float Y;
   
    public const int __ID__ = 1894465732;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "X:" + X + ","
        + "Y:" + Y + ","
        + "}";
    }
}
}

