
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class BotInfoConfigCategory
{
    private readonly System.Collections.Generic.Dictionary<int, BotInfoConfig> _dataMap;
    private readonly System.Collections.Generic.List<BotInfoConfig> _dataList;
    
    public BotInfoConfigCategory(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, BotInfoConfig>(n);
        _dataList = new System.Collections.Generic.List<BotInfoConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            BotInfoConfig _v;
            _v = global::cfg.BotInfoConfig.DeserializeBotInfoConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.BotId, _v);
        }

        PostInit();
    }

    public System.Collections.Generic.Dictionary<int, BotInfoConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BotInfoConfig> DataList => _dataList;

    public BotInfoConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BotInfoConfig Get(int key) => _dataMap[key];
    public BotInfoConfig this[int key] => _dataMap[key];

    public void ResolveRef(ConfigManager tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }

        PostResolve();
    }


    partial void PostInit();
    partial void PostResolve();
}

}

