
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class BotInfoConfig : Luban.BeanBase
{
    public BotInfoConfig(ByteBuf _buf) 
    {
        BotId = _buf.ReadInt();
        Name = _buf.ReadString();
        HeadRes = _buf.ReadString();
        {int n0 = _buf.ReadSize(); ItemInitialize = new System.Collections.Generic.List<ItemGroup>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ItemGroup _e0;  _e0 = global::cfg.ItemGroup.DeserializeItemGroup(_buf); ItemInitialize.Add(_e0);}}
    }

    public static BotInfoConfig DeserializeBotInfoConfig(ByteBuf _buf)
    {
        return new BotInfoConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int BotId;
    /// <summary>
    /// 昵称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 头像资源
    /// </summary>
    public readonly string HeadRes;
    /// <summary>
    /// 初始化道具
    /// </summary>
    public readonly System.Collections.Generic.List<ItemGroup> ItemInitialize;
   
    public const int __ID__ = 1979209367;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        foreach (var _e in ItemInitialize) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "BotId:" + BotId + ","
        + "Name:" + Name + ","
        + "HeadRes:" + HeadRes + ","
        + "ItemInitialize:" + Luban.StringUtil.CollectionToString(ItemInitialize) + ","
        + "}";
    }
}
}

