
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// BUFF类型
    /// </summary>
    public enum BuffType
    {
        /// <summary>
        /// 增益效果
        /// </summary>
        Buff = 1,
        /// <summary>
        /// 减益效果
        /// </summary>
        DeBuff = 2,
    }

} 

