
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// BUFF参数变化
/// </summary>
public sealed partial class BuffChange : Luban.BeanBase
{
    public BuffChange(ByteBuf _buf) 
    {
        Type = (ChangeType)_buf.ReadInt();
        Value = _buf.ReadFloat();
    }

    public static BuffChange DeserializeBuffChange(ByteBuf _buf)
    {
        return new BuffChange(_buf);
    }

    /// <summary>
    /// 参数类型
    /// </summary>
    public readonly ChangeType Type;
    /// <summary>
    /// 参数值
    /// </summary>
    public readonly float Value;
   
    public const int __ID__ = -1377476093;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Type:" + Type + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

