
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 参数类型
    /// </summary>
    public enum ChangeType
    {
        /// <summary>
        /// 速度（百分比，丢弃）
        /// </summary>
        SpeedAddPct = 1,
        /// <summary>
        /// 速度（固定值）
        /// </summary>
        SpeedAddValue = 2,
        /// <summary>
        /// 里程（百分比）
        /// </summary>
        MileageAddPct = 3,
        /// <summary>
        /// 里程（固定值）
        /// </summary>
        MileageAddValue = 4,
        /// <summary>
        /// 速度（百分比）
        /// </summary>
        SpeedDelPct = 5,
        /// <summary>
        /// 速度（固定值）
        /// </summary>
        SpeedDelValue = 6,
        /// <summary>
        /// 里程（百分比）
        /// </summary>
        MileageDelPct = 7,
        /// <summary>
        /// 里程（固定值）
        /// </summary>
        MileageDelValue = 8,
        /// <summary>
        /// 护盾（增加固定值）有护盾时减速不生效
        /// </summary>
        ShieldAdd = 9,
        /// <summary>
        /// 护盾（减少固定值）护盾值为0时减速生效
        /// </summary>
        ShieldDel = 10,
    }

} 

