
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class ConfigManager
{
    public Fight.FightRoomConfigCategory FightRoomConfigCategory {get; }
    public Fight.DeviceInfoConfigCategory DeviceInfoConfigCategory {get; }
    public Fight.DeviceStateConfigCategory DeviceStateConfigCategory {get; }
    public Fight.SceneInfoConfigCategory SceneInfoConfigCategory {get; }
    public Fight.SceneGroupInfoConfigCategory SceneGroupInfoConfigCategory {get; }
    public Fight.BuffIndexConfigCategory BuffIndexConfigCategory {get; }
    public Fight.FactionGroupConfigCategory FactionGroupConfigCategory {get; }
    public Fight.EffectInfoConfigCategory EffectInfoConfigCategory {get; }
    public Fight.BuffMutexConfigCategory BuffMutexConfigCategory {get; }
    public Item.ItemInfoConfigCategory ItemInfoConfigCategory {get; }
    public Item.InputIndexConfigCategory InputIndexConfigCategory {get; }
    public Item.StoreConfigCategory StoreConfigCategory {get; }
    public Item.SignInfoConfigCategory SignInfoConfigCategory {get; }
    public Item.StarInfoConfigCategory StarInfoConfigCategory {get; }
    public Item.BadgeInfoConfigCategory BadgeInfoConfigCategory {get; }
    public Global.ConstConfigCategory ConstConfigCategory {get; }
    public Global.NoticeConfigCategory NoticeConfigCategory {get; }
    public Global.ShieldedLibraryConfigCategory ShieldedLibraryConfigCategory {get; }
    public Global.RandomNamesConfigCategory RandomNamesConfigCategory {get; }
    public Rank.RankInfoConfigCategory RankInfoConfigCategory {get; }
    public Rank.RankRewardConfigCategory RankRewardConfigCategory {get; }
    public Rank.WeekRewardShowConfigCategory WeekRewardShowConfigCategory {get; }
    public Rank.SignRewardConfigCategory SignRewardConfigCategory {get; }
    public Rank.StarRewardConfigCategory StarRewardConfigCategory {get; }
    public Rank.VideoShowConfigCategory VideoShowConfigCategory {get; }
    public BotInfoConfigCategory BotInfoConfigCategory {get; }
    public Net.NetInfoConfigCategory NetInfoConfigCategory {get; }
    public Net.LoginInfoConfigCategory LoginInfoConfigCategory {get; }

    public ConfigManager(System.Func<string, ByteBuf> loader)
    {
        FightRoomConfigCategory = new Fight.FightRoomConfigCategory(loader("fight_fightroomconfigcategory"));
        DeviceInfoConfigCategory = new Fight.DeviceInfoConfigCategory(loader("fight_deviceinfoconfigcategory"));
        DeviceStateConfigCategory = new Fight.DeviceStateConfigCategory(loader("fight_devicestateconfigcategory"));
        SceneInfoConfigCategory = new Fight.SceneInfoConfigCategory(loader("fight_sceneinfoconfigcategory"));
        SceneGroupInfoConfigCategory = new Fight.SceneGroupInfoConfigCategory(loader("fight_scenegroupinfoconfigcategory"));
        BuffIndexConfigCategory = new Fight.BuffIndexConfigCategory(loader("fight_buffindexconfigcategory"));
        FactionGroupConfigCategory = new Fight.FactionGroupConfigCategory(loader("fight_factiongroupconfigcategory"));
        EffectInfoConfigCategory = new Fight.EffectInfoConfigCategory(loader("fight_effectinfoconfigcategory"));
        BuffMutexConfigCategory = new Fight.BuffMutexConfigCategory(loader("fight_buffmutexconfigcategory"));
        ItemInfoConfigCategory = new Item.ItemInfoConfigCategory(loader("item_iteminfoconfigcategory"));
        InputIndexConfigCategory = new Item.InputIndexConfigCategory(loader("item_inputindexconfigcategory"));
        StoreConfigCategory = new Item.StoreConfigCategory(loader("item_storeconfigcategory"));
        SignInfoConfigCategory = new Item.SignInfoConfigCategory(loader("item_signinfoconfigcategory"));
        StarInfoConfigCategory = new Item.StarInfoConfigCategory(loader("item_starinfoconfigcategory"));
        BadgeInfoConfigCategory = new Item.BadgeInfoConfigCategory(loader("item_badgeinfoconfigcategory"));
        ConstConfigCategory = new Global.ConstConfigCategory(loader("global_constconfigcategory"));
        NoticeConfigCategory = new Global.NoticeConfigCategory(loader("global_noticeconfigcategory"));
        ShieldedLibraryConfigCategory = new Global.ShieldedLibraryConfigCategory(loader("global_shieldedlibraryconfigcategory"));
        RandomNamesConfigCategory = new Global.RandomNamesConfigCategory(loader("global_randomnamesconfigcategory"));
        RankInfoConfigCategory = new Rank.RankInfoConfigCategory(loader("rank_rankinfoconfigcategory"));
        RankRewardConfigCategory = new Rank.RankRewardConfigCategory(loader("rank_rankrewardconfigcategory"));
        WeekRewardShowConfigCategory = new Rank.WeekRewardShowConfigCategory(loader("rank_weekrewardshowconfigcategory"));
        SignRewardConfigCategory = new Rank.SignRewardConfigCategory(loader("rank_signrewardconfigcategory"));
        StarRewardConfigCategory = new Rank.StarRewardConfigCategory(loader("rank_starrewardconfigcategory"));
        VideoShowConfigCategory = new Rank.VideoShowConfigCategory(loader("rank_videoshowconfigcategory"));
        BotInfoConfigCategory = new BotInfoConfigCategory(loader("botinfoconfigcategory"));
        NetInfoConfigCategory = new Net.NetInfoConfigCategory(loader("net_netinfoconfigcategory"));
        LoginInfoConfigCategory = new Net.LoginInfoConfigCategory(loader("net_logininfoconfigcategory"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        FightRoomConfigCategory.ResolveRef(this);
        DeviceInfoConfigCategory.ResolveRef(this);
        DeviceStateConfigCategory.ResolveRef(this);
        SceneInfoConfigCategory.ResolveRef(this);
        SceneGroupInfoConfigCategory.ResolveRef(this);
        BuffIndexConfigCategory.ResolveRef(this);
        FactionGroupConfigCategory.ResolveRef(this);
        EffectInfoConfigCategory.ResolveRef(this);
        BuffMutexConfigCategory.ResolveRef(this);
        ItemInfoConfigCategory.ResolveRef(this);
        InputIndexConfigCategory.ResolveRef(this);
        StoreConfigCategory.ResolveRef(this);
        SignInfoConfigCategory.ResolveRef(this);
        StarInfoConfigCategory.ResolveRef(this);
        BadgeInfoConfigCategory.ResolveRef(this);
        ConstConfigCategory.ResolveRef(this);
        NoticeConfigCategory.ResolveRef(this);
        ShieldedLibraryConfigCategory.ResolveRef(this);
        RandomNamesConfigCategory.ResolveRef(this);
        RankInfoConfigCategory.ResolveRef(this);
        RankRewardConfigCategory.ResolveRef(this);
        WeekRewardShowConfigCategory.ResolveRef(this);
        SignRewardConfigCategory.ResolveRef(this);
        StarRewardConfigCategory.ResolveRef(this);
        VideoShowConfigCategory.ResolveRef(this);
        BotInfoConfigCategory.ResolveRef(this);
        NetInfoConfigCategory.ResolveRef(this);
        LoginInfoConfigCategory.ResolveRef(this);
    }
}

}
