
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum dayOfWeek
    {
        周日 = 0,
        周一 = 1,
        周二 = 2,
        周三 = 3,
        周四 = 4,
        周五 = 5,
        周六 = 6,
    }

} 

