
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 指令
    /// </summary>
    public enum ECmd
    {
        /// <summary>
        /// 无效，占位用
        /// </summary>
        None = 0,
        /// <summary>
        /// 进入周榜后切换载具皮肤
        /// </summary>
        变形 = 1,
        /// <summary>
        /// 显示对应玩家的油桶数量
        /// </summary>
        查询 = 2,
        /// <summary>
        /// 使用油桶兑换指定编号的皮肤
        /// </summary>
        兑换 = 3,
        /// <summary>
        /// 使用默认皮肤（包括特效）
        /// </summary>
        恢复 = 4,
        /// <summary>
        /// 使用已拥有的指定编号皮肤
        /// </summary>
        更换 = 5,
        /// <summary>
        /// 使用当前周榜皮肤
        /// </summary>
        还原 = 6,
        /// <summary>
        /// 创建或加入对应姓氏或生肖的阵营
        /// </summary>
        加 = 7,
        /// <summary>
        /// 切换性别
        /// </summary>
        切换 = 8,
        /// <summary>
        /// 创建或加入对应姓氏或生肖的阵营
        /// </summary>
        加入 = 100,
        /// <summary>
        /// 普通加速（对应BUFFID)
        /// </summary>
        点赞 = 101,
        /// <summary>
        /// 仙女棒*1
        /// </summary>
        BasicSpeed = 111,
        /// <summary>
        /// 仙女棒*66
        /// </summary>
        BasicSpeed66 = 112,
        /// <summary>
        /// 仙女棒*188
        /// </summary>
        BasicSpeed188 = 113,
        /// <summary>
        /// 仙女棒*520
        /// </summary>
        BasicSpeed520 = 114,
        /// <summary>
        /// 仙女棒*999
        /// </summary>
        BasicSpeed999 = 115,
        /// <summary>
        /// 仙女棒*1314
        /// </summary>
        BasicSpeed1314 = 116,
        /// <summary>
        /// 能力药丸*1
        /// </summary>
        BasicBoom = 121,
        /// <summary>
        /// 能力药丸*10
        /// </summary>
        BasicBoom10 = 122,
        /// <summary>
        /// 能力药丸*66
        /// </summary>
        BasicBoom66 = 123,
        /// <summary>
        /// 能力药丸*188
        /// </summary>
        BasicBoom188 = 124,
        /// <summary>
        /// 能力药丸*520
        /// </summary>
        BasicBoom520 = 125,
        /// <summary>
        /// 能力药丸*999
        /// </summary>
        BasicBoom999 = 126,
        /// <summary>
        /// 能力药丸*1314
        /// </summary>
        BasicBoom1314 = 127,
        /// <summary>
        /// 甜甜圈*1
        /// </summary>
        AdvanceSpeed = 131,
        /// <summary>
        /// 甜甜圈*10
        /// </summary>
        AdvanceSpeed10 = 132,
        /// <summary>
        /// 甜甜圈*66
        /// </summary>
        AdvanceSpeed66 = 133,
        /// <summary>
        /// 甜甜圈*188
        /// </summary>
        AdvanceSpeed188 = 134,
        /// <summary>
        /// 甜甜圈*520
        /// </summary>
        AdvanceSpeed520 = 135,
        /// <summary>
        /// 能量电池*1
        /// </summary>
        AdvanceBoom = 141,
        /// <summary>
        /// 能量电池*10
        /// </summary>
        AdvanceBoom10 = 142,
        /// <summary>
        /// 能量电池*20
        /// </summary>
        AdvanceBoom20 = 143,
        /// <summary>
        /// 能量电池*66
        /// </summary>
        AdvanceBoom66 = 144,
        /// <summary>
        /// 能量电池*188
        /// </summary>
        AdvanceBoom188 = 145,
        /// <summary>
        /// 爱的爆炸*1
        /// </summary>
        SuperSpeed = 151,
        /// <summary>
        /// 爱的爆炸*6
        /// </summary>
        SuperSpeed6 = 152,
        /// <summary>
        /// 爱的爆炸*10
        /// </summary>
        SuperSpeed10 = 153,
        /// <summary>
        /// 爱的爆炸*18
        /// </summary>
        SuperSpeed18 = 154,
        /// <summary>
        /// 爱的爆炸*25
        /// </summary>
        SuperSpeed25 = 155,
        /// <summary>
        /// 爱的爆炸*55
        /// </summary>
        SuperSpeed55 = 156,
        /// <summary>
        /// 爱的爆炸*66
        /// </summary>
        SuperSpeed66 = 157,
        /// <summary>
        /// 神秘空投*1
        /// </summary>
        SeniorSpeed = 161,
        /// <summary>
        /// 神秘空投*6
        /// </summary>
        SeniorSpeed6 = 162,
        /// <summary>
        /// 神秘空投*10
        /// </summary>
        SeniorSpeed10 = 163,
        /// <summary>
        /// 神秘空投*18
        /// </summary>
        SeniorSpeed18 = 164,
        /// <summary>
        /// 神秘空投*25
        /// </summary>
        SeniorSpeed25 = 165,
        /// <summary>
        /// 神秘空投*55
        /// </summary>
        SeniorSpeed55 = 166,
    }

} 

