
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 特效类型
    /// </summary>
    public enum EffectType
    {
        /// <summary>
        /// 粒子
        /// </summary>
        Particle = 1,
        /// <summary>
        /// Spine动画
        /// </summary>
        Spine = 2,
    }

} 

