
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 特效组
/// </summary>
public sealed partial class Effect : Luban.BeanBase
{
    public Effect(ByteBuf _buf) 
    {
        DeviceId = _buf.ReadInt();
        DeviceId_Ref = null;
        EffectId = _buf.ReadInt();
        EffectSkin = _buf.ReadInt();
    }

    public static Effect DeserializeEffect(ByteBuf _buf)
    {
        return new Effect(_buf);
    }

    /// <summary>
    /// 皮肤ID，0表示通用
    /// </summary>
    public readonly int DeviceId;
    public Fight.DeviceInfoConfig DeviceId_Ref;
    /// <summary>
    /// 特效ID
    /// </summary>
    public readonly int EffectId;
    /// <summary>
    /// 特效皮肤ID
    /// </summary>
    public readonly int EffectSkin;
   
    public const int __ID__ = 2072749489;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        DeviceId_Ref = tables.DeviceInfoConfigCategory.GetOrDefault(DeviceId);
    }

    public override string ToString()
    {
        return "{ "
        + "DeviceId:" + DeviceId + ","
        + "EffectId:" + EffectId + ","
        + "EffectSkin:" + EffectSkin + ","
        + "}";
    }
}
}

