
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 战斗房间类型
    /// </summary>
    public enum FightRoomType
    {
        /// <summary>
        /// 姓氏房间
        /// </summary>
        TextRoom = 1,
        /// <summary>
        /// 生肖房间
        /// </summary>
        ZodiacRoom = 2,
        /// <summary>
        /// 自由房间
        /// </summary>
        FreeRoom = 3,
    }

} 

