
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum InteractiveID
    {
        None = 0,
        /// <summary>
        /// 礼物1
        /// </summary>
        礼物1 = 1,
        /// <summary>
        /// 礼物2
        /// </summary>
        礼物2 = 2,
        /// <summary>
        /// 礼物3
        /// </summary>
        礼物3 = 3,
        /// <summary>
        /// 礼物4
        /// </summary>
        礼物4 = 4,
        /// <summary>
        /// 礼物5
        /// </summary>
        礼物5 = 5,
        /// <summary>
        /// 礼物6
        /// </summary>
        礼物6 = 6,
        /// <summary>
        /// 点赞
        /// </summary>
        点赞 = 101,
        /// <summary>
        /// 弹幕
        /// </summary>
        弹幕 = 102,
        /// <summary>
        /// 模糊匹配弹幕
        /// </summary>
        模糊匹配弹幕 = 103,
        /// <summary>
        /// 快_礼物1
        /// </summary>
        快_礼物1 = 1001,
        /// <summary>
        /// 快_礼物2
        /// </summary>
        快_礼物2 = 1002,
        /// <summary>
        /// 快_礼物3
        /// </summary>
        快_礼物3 = 1003,
        /// <summary>
        /// 快_礼物4
        /// </summary>
        快_礼物4 = 1004,
        /// <summary>
        /// 快_礼物5
        /// </summary>
        快_礼物5 = 1005,
        /// <summary>
        /// 快_礼物6
        /// </summary>
        快_礼物6 = 1006,
        /// <summary>
        /// 快_点赞
        /// </summary>
        快_点赞 = 1101,
        /// <summary>
        /// 快_弹幕
        /// </summary>
        快_弹幕 = 1102,
        /// <summary>
        /// 快_模糊匹配弹幕
        /// </summary>
        快_模糊匹配弹幕 = 1103,
    }

} 

