
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ItemType
    {
        /// <summary>
        /// 占位
        /// </summary>
        None = 0,
        /// <summary>
        /// 货币
        /// </summary>
        Coin = 1,
        /// <summary>
        /// 载具皮肤
        /// </summary>
        DeviceSkin = 2,
        /// <summary>
        /// 道具皮肤
        /// </summary>
        ItemSkin = 3,
        /// <summary>
        /// 卡牌
        /// </summary>
        Card = 4,
        /// <summary>
        /// 头像框
        /// </summary>
        Frame = 5,
        /// <summary>
        /// 入场CG
        /// </summary>
        LoginCG = 6,
    }

} 

