
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 道具组
/// </summary>
public sealed partial class ItemGroup : Luban.BeanBase
{
    public ItemGroup(ByteBuf _buf) 
    {
        ItemId = _buf.ReadInt();
        ItemId_Ref = null;
        Number = _buf.ReadLong();
    }

    public static ItemGroup DeserializeItemGroup(ByteBuf _buf)
    {
        return new ItemGroup(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int ItemId;
    public Item.ItemInfoConfig ItemId_Ref;
    /// <summary>
    /// 道具数量
    /// </summary>
    public readonly long Number;
   
    public const int __ID__ = -159408372;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        ItemId_Ref = tables.ItemInfoConfigCategory.GetOrDefault(ItemId);
    }

    public override string ToString()
    {
        return "{ "
        + "ItemId:" + ItemId + ","
        + "Number:" + Number + ","
        + "}";
    }
}
}

