
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 场景信息组
/// </summary>
public sealed partial class LayerInfo : Luban.BeanBase
{
    public LayerInfo(ByteBuf _buf) 
    {
        {int n0 = _buf.ReadSize(); LayerWeight = new System.Collections.Generic.List<LayerWeight>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { LayerWeight _e0;  _e0 = global::cfg.LayerWeight.DeserializeLayerWeight(_buf); LayerWeight.Add(_e0);}}
        Speed = _buf.ReadFloat();
        IsBlur = _buf.ReadBool();
    }

    public static LayerInfo DeserializeLayerInfo(ByteBuf _buf)
    {
        return new LayerInfo(_buf);
    }

    /// <summary>
    /// 场景权重组
    /// </summary>
    public readonly System.Collections.Generic.List<LayerWeight> LayerWeight;
    /// <summary>
    /// 场景移动速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 是否有模糊资源需要拼接
    /// </summary>
    public readonly bool IsBlur;
   
    public const int __ID__ = 339197311;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
        foreach (var _e in LayerWeight) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "LayerWeight:" + Luban.StringUtil.CollectionToString(LayerWeight) + ","
        + "Speed:" + Speed + ","
        + "IsBlur:" + IsBlur + ","
        + "}";
    }
}
}

