
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 场景权重组
/// </summary>
public sealed partial class LayerWeight : Luban.BeanBase
{
    public LayerWeight(ByteBuf _buf) 
    {
        LayerRes = _buf.ReadString();
        Weight = _buf.ReadInt();
    }

    public static LayerWeight DeserializeLayerWeight(ByteBuf _buf)
    {
        return new LayerWeight(_buf);
    }

    /// <summary>
    /// 场景资源名
    /// </summary>
    public readonly string LayerRes;
    /// <summary>
    /// 场景权重
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = -56317175;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "LayerRes:" + LayerRes + ","
        + "Weight:" + Weight + ","
        + "}";
    }
}
}

