
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 参数互斥
/// </summary>
public sealed partial class MutexChange : Luban.BeanBase
{
    public MutexChange(ByteBuf _buf) 
    {
        Type = (ChangeType)_buf.ReadInt();
        MutexBool = _buf.ReadBool();
    }

    public static MutexChange DeserializeMutexChange(ByteBuf _buf)
    {
        return new MutexChange(_buf);
    }

    /// <summary>
    /// 参数类型
    /// </summary>
    public readonly ChangeType Type;
    /// <summary>
    /// 假：累加，真：替换（或无视）
    /// </summary>
    public readonly bool MutexBool;
   
    public const int __ID__ = -581222929;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Type:" + Type + ","
        + "MutexBool:" + MutexBool + ","
        + "}";
    }
}
}

