
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum NameTitleBg
    {
        /// <summary>
        /// 占位
        /// </summary>
        None = 0,
        /// <summary>
        /// 黄金标签
        /// </summary>
        bg_name01 = 1,
        /// <summary>
        /// 蓝色标签
        /// </summary>
        bg_name02 = 2,
    }

} 

