
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 动态场景
/// </summary>
public sealed partial class Planning : Luban.BeanBase
{
    public Planning(ByteBuf _buf) 
    {
        TimePlanning = _buf.ReadInt();
        FightScene = _buf.ReadInt();
        BaseSpeed = _buf.ReadInt();
    }

    public static Planning DeserializePlanning(ByteBuf _buf)
    {
        return new Planning(_buf);
    }

    /// <summary>
    /// 场景触发时刻
    /// </summary>
    public readonly int TimePlanning;
    /// <summary>
    /// 场景ID
    /// </summary>
    public readonly int FightScene;
    /// <summary>
    /// 场内基准移动速度
    /// </summary>
    public readonly int BaseSpeed;
   
    public const int __ID__ = 1934019453;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TimePlanning:" + TimePlanning + ","
        + "FightScene:" + FightScene + ","
        + "BaseSpeed:" + BaseSpeed + ","
        + "}";
    }
}
}

