
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 特效挂载点
    /// </summary>
    public enum PointType
    {
        /// <summary>
        /// 本体-E0（两轮中心）
        /// </summary>
        E0 = 0,
        /// <summary>
        /// 本体前方-E6
        /// </summary>
        E6 = 1,
        /// <summary>
        /// 本体后方-E1
        /// </summary>
        E1 = 2,
        /// <summary>
        /// 前轮-E5
        /// </summary>
        E5 = 3,
        /// <summary>
        /// 后轮-E4
        /// </summary>
        E4 = 4,
        /// <summary>
        /// 尾翼-M1
        /// </summary>
        M1 = 5,
        /// <summary>
        /// 尾翼喷射-ME
        /// </summary>
        ME = 6,
        /// <summary>
        /// 场景（不跟随车辆挂点）
        /// </summary>
        A0 = 7,
        /// <summary>
        /// 本体后方-E0高达专用
        /// </summary>
        E2 = 8,
    }

} 

