
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum RankType
    {
        /// <summary>
        /// 占位
        /// </summary>
        None = 0,
        /// <summary>
        /// 七天榜
        /// </summary>
        WeekRank = 1,
        /// <summary>
        /// 粉丝榜
        /// </summary>
        FansRank = 2,
        /// <summary>
        /// 月度榜
        /// </summary>
        MonthRank = 3,
        /// <summary>
        /// 上周榜
        /// </summary>
        PreviousWeekRank = 4,
        /// <summary>
        /// 上月榜
        /// </summary>
        PreviousMonthRank = 5,
        /// <summary>
        /// 上里程榜
        /// </summary>
        PreviousMilestone = 6,
        /// <summary>
        /// 名人堂
        /// </summary>
        HallOfFame = 7,
        /// <summary>
        /// 里程碑
        /// </summary>
        Milestone = 8,
        /// <summary>
        /// 秒榜
        /// </summary>
        KillRank = 9,
    }

} 

