
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum RankEnum
    {
        /// <summary>
        /// 占位
        /// </summary>
        None = 0,
        /// <summary>
        /// 日
        /// </summary>
        Day = 1,
        /// <summary>
        /// 周
        /// </summary>
        Week = 2,
        /// <summary>
        /// 月
        /// </summary>
        Month = 3,
        /// <summary>
        /// 永久
        /// </summary>
        Forever = 4,
        /// <summary>
        /// 半月，按两周算
        /// </summary>
        HalfMonth = 5,
        /// <summary>
        /// 即时（请求则刷新）
        /// </summary>
        Instant = 6,
    }

} 

