
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 礼物组策略
/// </summary>
public sealed partial class SECmd : Luban.BeanBase
{
    public SECmd(ByteBuf _buf) 
    {
        Number = _buf.ReadInt();
        ECmd = (ECmd)_buf.ReadInt();
    }

    public static SECmd DeserializeSECmd(ByteBuf _buf)
    {
        return new SECmd(_buf);
    }

    /// <summary>
    /// 条件数量
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// 对应事件指令
    /// </summary>
    public readonly ECmd ECmd;
   
    public const int __ID__ = 78775688;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Number:" + Number + ","
        + "ECmd:" + ECmd + ","
        + "}";
    }
}
}

