
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 载具状态
    /// </summary>
    public enum State
    {
        /// <summary>
        /// 停止状态(不切换）
        /// </summary>
        None = 0,
        /// <summary>
        /// 起步状态
        /// </summary>
        Start = 1,
        /// <summary>
        /// 正常状态
        /// </summary>
        Normal = 2,
        /// <summary>
        /// 加速状态
        /// </summary>
        Fast = 3,
        /// <summary>
        /// 受击状态
        /// </summary>
        Hit = 4,
        /// <summary>
        /// 超级加速（无敌）
        /// </summary>
        Invincible = 5,
        /// <summary>
        /// 损坏状态
        /// </summary>
        Damaged = 6,
    }

} 

