
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
/// <summary>
/// 状态互斥
/// </summary>
public sealed partial class StateChange : Luban.BeanBase
{
    public StateChange(ByteBuf _buf) 
    {
        State = (State)_buf.ReadInt();
        MutexBool = _buf.ReadBool();
    }

    public static StateChange DeserializeStateChange(ByteBuf _buf)
    {
        return new StateChange(_buf);
    }

    /// <summary>
    /// 状态类型
    /// </summary>
    public readonly State State;
    /// <summary>
    /// 假：累加，真：替换（或无视）
    /// </summary>
    public readonly bool MutexBool;
   
    public const int __ID__ = -1904936063;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(ConfigManager tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "State:" + State + ","
        + "MutexBool:" + MutexBool + ","
        + "}";
    }
}
}

