
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 目标
    /// </summary>
    public enum Target
    {
        /// <summary>
        /// 自身
        /// </summary>
        MySelf = 1,
        /// <summary>
        /// 随机敌方
        /// </summary>
        Random = 2,
        /// <summary>
        /// 排名靠前的敌方
        /// </summary>
        Top = 3,
    }

} 

