
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 生肖文本组
    /// </summary>
    public enum ZodiacName
    {
        /// <summary>
        /// 鼠
        /// </summary>
        鼠 = 1,
        /// <summary>
        /// 牛
        /// </summary>
        牛 = 2,
        /// <summary>
        /// 虎
        /// </summary>
        虎 = 3,
        /// <summary>
        /// 兔
        /// </summary>
        兔 = 4,
        /// <summary>
        /// 龙
        /// </summary>
        龙 = 5,
        /// <summary>
        /// 蛇
        /// </summary>
        蛇 = 6,
        /// <summary>
        /// 马
        /// </summary>
        马 = 7,
        /// <summary>
        /// 羊
        /// </summary>
        羊 = 8,
        /// <summary>
        /// 猴
        /// </summary>
        猴 = 9,
        /// <summary>
        /// 鸡
        /// </summary>
        鸡 = 10,
        /// <summary>
        /// 狗
        /// </summary>
        狗 = 11,
        /// <summary>
        /// 猪
        /// </summary>
        猪 = 12,
    }

} 

